/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Data.ZMod.QuotientGroup
public import Mathlib.GroupTheory.Complement
public import Mathlib.GroupTheory.SpecificGroups.Dihedral
public import TauCeti.Algebra.Group.Subgroup.ZPowers

/-!
# The dihedral groups: an enumeration, a recognition criterion, and the rotation subgroup

`DihedralGroup n` is finite, but `Fintype` alone does not hand back a list of its elements, since
`Finset.toList` is noncomputable. This file writes that list down, and evaluates
`DihedralGroup.exponent` — which computes the exponent of `DihedralGroup n` as `lcm n 2` — at the
two orders the worked examples of the Burnside--Dixon--Schneider character-table algorithm are run
on.

It then proves the recognition criterion: a group generated by two involutions, *neither of them
the identity*, is a dihedral group, of order twice the order of their product. Every rank-two
reflection group is presented to us in that shape, and this is what identifies it.

Finally it names the **rotation subgroup**. It is presented as the kernel of the reflection parity,
so that it is normal of index `2`; the defining dihedral relation is then recorded as
`TauCeti.conj_eq_inv_of_notMem_dihedralRotations`, that conjugation by anything outside it inverts
every rotation. Its cyclic coordinate is `TauCeti.dihedralRotationsMulEquiv`; the characters of the
rotation subgroup that coordinate names are in
`TauCeti.GroupTheory.SpecificGroups.Dihedral.Character`. The other subgroup the dihedral relation
distinguishes, the two-element subgroup `{1, sr i}` generated by a single reflection, is described
last: it is nontrivial, and proper except in `DihedralGroup 1`. The two subgroups are complementary
at every degree, finite or not, which is the semidirect decomposition `DihedralGroup n = C_n ⋊ C₂`.

## Main definitions

* `TauCeti.dihedralElements`: a computable enumeration of `DihedralGroup n`.
* `TauCeti.dihedralHom`: the homomorphism `DihedralGroup n →* G` attached to two involutions whose
  product has order `n`.
* `TauCeti.dihedralGroupMulEquiv`: that homomorphism as an isomorphism, when the two involutions
  generate `G` and neither is the identity.
* `TauCeti.dihedralReflectionParity`, `TauCeti.dihedralRotations`: the reflection parity and the
  rotation subgroup it cuts out, with `TauCeti.dihedralRotationsMulEquiv` its cyclic coordinate.

## Main results

* `TauCeti.mem_dihedralElements`: that enumeration exhausts the group.
* `TauCeti.exponent_dihedralGroup_three`: `DihedralGroup 3`, of order `6`, has exponent `6`.
* `TauCeti.exponent_dihedralGroup_four`: `DihedralGroup 4`, of order `8`, has exponent `4`.
* `TauCeti.dihedralHom_injective` and `TauCeti.range_dihedralHom`: the dihedral group of order
  twice the order of the product of two involutions other than the identity embeds onto the
  subgroup they generate.
* `TauCeti.dihedralHom_bijective` and `TauCeti.nonempty_dihedralGroup_mulEquiv`: **a group generated
  by two involutions other than the identity is the dihedral group of order twice the order of
  their product.**
* `TauCeti.index_dihedralRotations` and `TauCeti.card_dihedralRotations`: the rotation subgroup
  has index `2` and order `n`.
* `TauCeti.mem_zpowers_dihedralSr_iff`: the subgroup generated by a reflection is the two-element
  subgroup `{1, sr i}`, with `TauCeti.dihedralSr_ne_one` and
  `TauCeti.zpowers_dihedralSr_ne_top` reading off that it is nontrivial, and proper except in
  `DihedralGroup 1`.
* `TauCeti.isComplement'_dihedralRotations_zpowers_sr`: **the rotation subgroup and the subgroup
  generated by a reflection are complementary**, at every degree, so
  `DihedralGroup n = C_n ⋊ C₂`.
* `TauCeti.conj_eq_inv_of_notMem_dihedralRotations` and
  `TauCeti.conjNormal_eq_inv_of_notMem_dihedralRotations`: **conjugation by a reflection inverts
  every rotation**, in the ambient group and inside the rotation subgroup.
-/

public section

namespace TauCeti

/-- The rotations `r 0, …, r (n-1)` of `DihedralGroup n`, each followed by the corresponding
reflection. For `n ≠ 0` this lists all `2 * n` elements of the group, which is
`TauCeti.mem_dihedralElements`. The body is exposed because a kernel computation over the group —
such as the class data of `TauCeti.dihedralClassData` — has to reduce it. -/
@[expose] def dihedralElements (n : ℕ) : List (DihedralGroup n) :=
  (List.range n).flatMap fun i : ℕ => [DihedralGroup.r (i : ZMod n), DihedralGroup.sr (i : ZMod n)]

/-- The enumeration `TauCeti.dihedralElements` exhausts the dihedral group. -/
theorem mem_dihedralElements {n : ℕ} [NeZero n] (g : DihedralGroup n) : g ∈ dihedralElements n := by
  cases g with
  | r i | sr i => exact List.mem_flatMap.mpr ⟨i.val, List.mem_range.mpr i.val_lt, by simp⟩

/-- The dihedral group of order `6`, the symmetric group on three letters, has exponent `6`. -/
@[simp]
theorem exponent_dihedralGroup_three : Monoid.exponent (DihedralGroup 3) = 6 := by
  rw [DihedralGroup.exponent]
  decide

/-- The dihedral group of order `8` has exponent `4`. -/
@[simp]
theorem exponent_dihedralGroup_four : Monoid.exponent (DihedralGroup 4) = 4 := by
  rw [DihedralGroup.exponent]
  decide

/-! ## Recognizing a dihedral group

A group generated by two involutions `s` and `t`, neither of them the identity, is dihedral: its
rotation subgroup is generated by `c = s * t`, and its reflections are the elements `s * c ^ k`.
Turning that into an isomorphism means indexing the powers of `c` by `ZMod n`, where `n` is the
order of `c`; the index `i` is read as the integer `ZMod.cast i`, and `TauCeti.dihedralHom` is the
resulting homomorphism. Taking that representative in `ℤ` rather than in `ℕ` costs nothing and
covers the modulus `n = 0`, where `ZMod 0` is `ℤ` and an element of order `0` is one of infinite
order: the criterion then recognizes the infinite dihedral group.

The work is in injectivity. On the rotations it is the definition of the order of `c`. On the
reflections it is the observation that `s * c ^ k = 1` puts `s` inside the *abelian* subgroup
generated by `c`, so that `s` both inverts and centralizes `c`; then `c` is its own inverse, and the
parity of `k` makes `s` or `t` the identity. Both hypotheses `s ≠ 1` and `t ≠ 1` are therefore
needed: for `s = 1` the group is generated by the single involution `t` while `orderOf (s * t) = 2`,
so it is not the dihedral group of order `4`. -/

section Recognition

variable {G : Type*} [Group G] {n : ℕ} {c s t : G}

/-- The power of `c` at an integer representative of an index is the power at *any* integer
representative of it, once `c` has order `n`. -/
private lemma zpow_cast_eq_zpow (hc : orderOf c = n) {i : ZMod n} {k : ℤ} (h : (k : ZMod n) = i) :
    c ^ (ZMod.cast i : ℤ) = c ^ k := by
  rw [zpow_eq_zpow_iff_modEq, hc, ← ZMod.intCast_eq_intCast_iff, ZMod.intCast_zmod_cast, h]

private lemma zpow_cast_zero {M : Type*} [DivInvMonoid M] (c : M) :
    c ^ (ZMod.cast (0 : ZMod n) : ℤ) = 1 := by
  rw [ZMod.cast_zero, zpow_zero]

private lemma zpow_cast_one (hc : orderOf c = n) : c ^ (ZMod.cast (1 : ZMod n) : ℤ) = c := by
  rw [zpow_cast_eq_zpow hc (k := 1) Int.cast_one, zpow_one]

private lemma zpow_cast_add (hc : orderOf c = n) (i j : ZMod n) :
    c ^ (ZMod.cast (i + j) : ℤ) = c ^ (ZMod.cast i : ℤ) * c ^ (ZMod.cast j : ℤ) := by
  rw [zpow_cast_eq_zpow hc (k := (ZMod.cast i : ℤ) + (ZMod.cast j : ℤ))
      (by rw [Int.cast_add, ZMod.intCast_zmod_cast, ZMod.intCast_zmod_cast]), zpow_add]

private lemma zpow_cast_neg (hc : orderOf c = n) (i : ZMod n) :
    c ^ (ZMod.cast (-i) : ℤ) = (c ^ (ZMod.cast i : ℤ))⁻¹ := by
  rw [zpow_cast_eq_zpow hc (k := -(ZMod.cast i : ℤ))
      (by rw [Int.cast_neg, ZMod.intCast_zmod_cast]), zpow_neg]

/-- A power of `c` at an index is trivial exactly at the index `0`. -/
private lemma zpow_cast_eq_one_iff (hc : orderOf c = n) {i : ZMod n} :
    c ^ (ZMod.cast i : ℤ) = 1 ↔ i = 0 := by
  rw [← zpow_zero c, zpow_eq_zpow_iff_modEq, hc, ← ZMod.intCast_eq_intCast_iff,
    ZMod.intCast_zmod_cast, Int.cast_zero]

/-- Either of the two involutions inverts their product by conjugation. -/
private lemma conj_mul_eq_inv {M : Type*} [DivisionMonoid M] {s t : M} (hs : s * s = 1)
    (ht : t * t = 1) :
    s * (s * t) * s⁻¹ = (s * t)⁻¹ := by
  rw [mul_inv_rev, inv_eq_of_mul_eq_one_right ht, inv_eq_of_mul_eq_one_right hs, ← mul_assoc, hs,
    one_mul]

/-- Moving one of the two involutions across a rotation inverts the rotation. -/
private lemma zpow_cast_mul_eq (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n)
    (i : ZMod n) :
    (s * t) ^ (ZMod.cast i : ℤ) * s = s * (s * t) ^ (ZMod.cast (-i) : ℤ) := by
  have hsi : s⁻¹ = s := inv_eq_of_mul_eq_one_right hs
  have hkey : s * (s * t) ^ (ZMod.cast i : ℤ) * s⁻¹ = ((s * t) ^ (ZMod.cast i : ℤ))⁻¹ := by
    rw [← conj_zpow, conj_mul_eq_inv hs ht, inv_zpow]
  rw [zpow_cast_neg hn, ← hkey, hsi, ← mul_assoc, ← mul_assoc, hs, one_mul]

/-- The underlying function of `TauCeti.dihedralHom`. -/
private def dihedralFun (s c : G) : DihedralGroup n → G
  | .r i => c ^ (ZMod.cast i : ℤ)
  | .sr i => s * c ^ (ZMod.cast i : ℤ)

private lemma dihedralFun_r (s c : G) (i : ZMod n) :
    dihedralFun s c (.r i) = c ^ (ZMod.cast i : ℤ) := rfl

private lemma dihedralFun_sr (s c : G) (i : ZMod n) :
    dihedralFun s c (.sr i) = s * c ^ (ZMod.cast i : ℤ) := rfl

/-- The homomorphism out of the dihedral group determined by two involutions whose product has
order `n`: a rotation `r i` goes to `(s * t) ^ i`, and a reflection `sr i` to `s * (s * t) ^ i`,
the index `i` being read as an integer by `ZMod.cast`. These two values are
`TauCeti.dihedralHom_r` and `TauCeti.dihedralHom_sr`. -/
def dihedralHom (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n) :
    DihedralGroup n →* G where
  toFun := dihedralFun s (s * t)
  map_one' := by rw [DihedralGroup.one_def, dihedralFun_r, zpow_cast_zero]
  map_mul' := by
    rintro (i | i) (j | j)
    · rw [DihedralGroup.r_mul_r, dihedralFun_r, dihedralFun_r, dihedralFun_r, zpow_cast_add hn]
    · rw [DihedralGroup.r_mul_sr, dihedralFun_sr, dihedralFun_r, dihedralFun_sr, ← mul_assoc,
        zpow_cast_mul_eq hs ht hn, mul_assoc, ← zpow_cast_add hn, neg_add_eq_sub]
    · rw [DihedralGroup.sr_mul_r, dihedralFun_sr, dihedralFun_sr, dihedralFun_r,
        zpow_cast_add hn, mul_assoc]
    · rw [DihedralGroup.sr_mul_sr, dihedralFun_r, dihedralFun_sr, dihedralFun_sr, ← mul_assoc,
        mul_assoc s, zpow_cast_mul_eq hs ht hn, ← mul_assoc, hs, one_mul, ← zpow_cast_add hn,
        neg_add_eq_sub]

/-- `TauCeti.dihedralHom` sends the rotation `r i` to the power `(s * t) ^ i`. -/
@[simp]
theorem dihedralHom_r (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n) (i : ZMod n) :
    dihedralHom hs ht hn (.r i) = (s * t) ^ (ZMod.cast i : ℤ) := by
  unfold dihedralHom
  exact dihedralFun_r s (s * t) i

/-- `TauCeti.dihedralHom` sends the reflection `sr i` to `s * (s * t) ^ i`. -/
@[simp]
theorem dihedralHom_sr (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n) (i : ZMod n) :
    dihedralHom hs ht hn (.sr i) = s * (s * t) ^ (ZMod.cast i : ℤ) := by
  unfold dihedralHom
  exact dihedralFun_sr s (s * t) i

/-- **Two involutions other than the identity embed the dihedral group.** If neither of the
involutions `s` and `t` is the identity, then `TauCeti.dihedralHom` is injective, where `n` is the
order of `s * t`. -/
theorem dihedralHom_injective (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1) (ht1 : t ≠ 1)
    (hn : orderOf (s * t) = n) : Function.Injective (dihedralHom hs ht hn) := by
  rw [injective_iff_map_eq_one]
  rintro (i | i) hi
  · -- A rotation in the kernel has index a multiple of the order of `s * t`, hence index zero.
    rw [dihedralHom_r, zpow_cast_eq_one_iff hn] at hi
    rw [hi, DihedralGroup.r_zero]
  · -- A reflection in the kernel would put `s` in the centralizer of `s * t`.
    rw [dihedralHom_sr] at hi
    exfalso
    have hzpow : s = (s * t) ^ (-(ZMod.cast i : ℤ)) := by
      rw [zpow_neg, eq_inv_iff_mul_eq_one]
      exact hi
    have hcomm : Commute s (s * t) := by
      have hz : Commute ((s * t) ^ (-(ZMod.cast i : ℤ))) (s * t) :=
        (Commute.refl (s * t)).zpow_left _
      rwa [← hzpow] at hz
    have hinv : (s * t)⁻¹ = s * t := by
      rw [← conj_mul_eq_inv hs ht, hcomm.eq, mul_inv_cancel_right]
    have hsq : (s * t) ^ (2 : ℤ) = 1 := by
      rw [zpow_two]
      nth_rewrite 1 [← hinv]
      exact inv_mul_cancel _
    rcases Int.even_or_odd (-(ZMod.cast i : ℤ)) with ⟨m, hm⟩ | ⟨m, hm⟩
    · exact hs1 (by rw [hzpow, hm, ← two_mul, zpow_mul, hsq, one_zpow])
    · refine ht1 (mul_left_cancel (a := s) ?_)
      rw [mul_one]
      nth_rewrite 2 [hzpow]
      rw [hm, zpow_add, zpow_mul, hsq, one_zpow, one_mul, zpow_one]

/-- The image of `TauCeti.dihedralHom` is the subgroup generated by the two involutions. -/
theorem range_dihedralHom (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n) :
    (dihedralHom hs ht hn).range = Subgroup.closure {s, t} := by
  have hsmem : s ∈ Subgroup.closure ({s, t} : Set G) := Subgroup.subset_closure (by simp)
  have hstmem : s * t ∈ Subgroup.closure ({s, t} : Set G) :=
    mul_mem hsmem (Subgroup.subset_closure (by simp))
  refine le_antisymm ?_ ?_
  · rintro _ ⟨i | i, rfl⟩
    · exact zpow_mem hstmem _
    · exact mul_mem hsmem (zpow_mem hstmem _)
  · rw [Subgroup.closure_le]
    rintro x (rfl | rfl)
    · exact ⟨DihedralGroup.sr 0, by rw [dihedralHom_sr, zpow_cast_zero, mul_one]⟩
    · exact ⟨DihedralGroup.sr 1, by rw [dihedralHom_sr, zpow_cast_one hn, ← mul_assoc, hs, one_mul]⟩

/-- **A group generated by two involutions other than the identity is dihedral.** If the
involutions `s` and `t` generate `G` and neither is the identity, then `TauCeti.dihedralHom`
identifies `G` with the dihedral group of order `2 * n`, where `n` is the order of `s * t`. -/
theorem dihedralHom_bijective (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1) (ht1 : t ≠ 1)
    (hn : orderOf (s * t) = n) (hgen : Subgroup.closure ({s, t} : Set G) = ⊤) :
    Function.Bijective (dihedralHom hs ht hn) :=
  ⟨dihedralHom_injective hs ht hs1 ht1 hn,
    MonoidHom.range_eq_top.mp (by rw [range_dihedralHom, hgen])⟩

/-- **A group generated by two involutions other than the identity is the dihedral group of order
twice the order of their product.** The isomorphism is `TauCeti.dihedralHom`: the rotation `r i` is
the power `(s * t) ^ i`, and the reflection `sr i` is `s * (s * t) ^ i`.

It is what identifies the Weyl group of a rank-two root system in
`TauCeti.nonempty_dihedralGroup_mulEquiv_weylGroup`. -/
noncomputable def dihedralGroupMulEquiv (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1)
    (ht1 : t ≠ 1) (hn : orderOf (s * t) = n) (hgen : Subgroup.closure ({s, t} : Set G) = ⊤) :
    DihedralGroup n ≃* G :=
  MulEquiv.ofBijective (dihedralHom hs ht hn) (dihedralHom_bijective hs ht hs1 ht1 hn hgen)

/-- `TauCeti.dihedralGroupMulEquiv` is `TauCeti.dihedralHom`. -/
@[simp]
theorem dihedralGroupMulEquiv_apply (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1) (ht1 : t ≠ 1)
    (hn : orderOf (s * t) = n) (hgen : Subgroup.closure ({s, t} : Set G) = ⊤)
    (x : DihedralGroup n) :
    dihedralGroupMulEquiv hs ht hs1 ht1 hn hgen x = dihedralHom hs ht hn x :=
  MulEquiv.ofBijective_apply _ _ x

/-- **A group generated by two involutions other than the identity is the dihedral group of order
twice the order of their product**, the existential form of
`TauCeti.dihedralGroupMulEquiv`. -/
theorem nonempty_dihedralGroup_mulEquiv (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1)
    (ht1 : t ≠ 1) (hn : orderOf (s * t) = n)
    (hgen : Subgroup.closure ({s, t} : Set G) = ⊤) :
    Nonempty (DihedralGroup n ≃* G) :=
  ⟨dihedralGroupMulEquiv hs ht hs1 ht1 hn hgen⟩

end Recognition

/-! ## The rotation subgroup

The rotations form a subgroup of index `2`, and the cleanest way to get it — together with its
normality — is as the kernel of the **reflection parity**, the homomorphism onto `ZMod 2` that
records whether an element is a rotation or a reflection. The relation that makes the dihedral
group dihedral, `s r s⁻¹ = r⁻¹`, is then the statement that conjugation by anything outside the
rotation subgroup inverts every rotation. -/

section Rotations

variable {n : ℕ}

/-- The **reflection parity** of a dihedral element: `0` on the rotations `r i` and `1` on the
reflections `sr i`. Written multiplicatively so that it is a `MonoidHom` whose kernel is the
rotation subgroup. -/
def dihedralReflectionParity (n : ℕ) : DihedralGroup n →* Multiplicative (ZMod 2) where
  toFun
    | DihedralGroup.r _ => 1
    | DihedralGroup.sr _ => Multiplicative.ofAdd 1
  map_one' := rfl
  map_mul' := by
    rintro (i | i) (j | j) <;>
      simp only [DihedralGroup.r_mul_r, DihedralGroup.r_mul_sr, DihedralGroup.sr_mul_r,
        DihedralGroup.sr_mul_sr] <;>
      decide

@[simp]
theorem dihedralReflectionParity_r (i : ZMod n) :
    dihedralReflectionParity n (DihedralGroup.r i) = 1 :=
  (rfl)

@[simp]
theorem dihedralReflectionParity_sr (i : ZMod n) :
    dihedralReflectionParity n (DihedralGroup.sr i) = Multiplicative.ofAdd 1 :=
  (rfl)

/-- The reflection parity is onto. -/
theorem dihedralReflectionParity_surjective (n : ℕ) :
    Function.Surjective (dihedralReflectionParity n) := by
  intro y
  fin_cases y
  exacts [⟨DihedralGroup.r 0, rfl⟩, ⟨DihedralGroup.sr 0, rfl⟩]

/-- The **rotation subgroup** of `DihedralGroup n`, the kernel of the reflection parity. It is
normal of index `2`, and `TauCeti.dihedralRotationsMulEquiv` identifies it with
`Multiplicative (ZMod n)`, so it is cyclic (`TauCeti.isCyclic_dihedralRotations`) and in particular
commutative. -/
def dihedralRotations (n : ℕ) : Subgroup (DihedralGroup n) :=
  (dihedralReflectionParity n).ker

instance dihedralRotations_normal (n : ℕ) : (dihedralRotations n).Normal :=
  (dihedralReflectionParity n).normal_ker

/-- Membership in the rotation subgroup is being a rotation. -/
@[simp]
theorem mem_dihedralRotations_iff {g : DihedralGroup n} :
    g ∈ dihedralRotations n ↔ ∃ i : ZMod n, g = DihedralGroup.r i := by
  cases g with
  | r i => exact iff_of_true (by simp [dihedralRotations, MonoidHom.mem_ker]) ⟨i, rfl⟩
  | sr i =>
    refine iff_of_false (by simp [dihedralRotations, MonoidHom.mem_ker]) ?_
    rintro ⟨j, hj⟩
    simp at hj

/-- A rotation lies in the rotation subgroup. Not a `simp` lemma: `simp` already closes this
through `TauCeti.mem_dihedralRotations_iff`; it is kept as the membership proof to hand to the
subtype constructor. -/
theorem r_mem_dihedralRotations (i : ZMod n) : DihedralGroup.r i ∈ dihedralRotations n :=
  mem_dihedralRotations_iff.mpr ⟨i, rfl⟩

/-- A reflection does not lie in the rotation subgroup. Not a `simp` lemma, for the same reason as
`TauCeti.r_mem_dihedralRotations`. -/
theorem sr_notMem_dihedralRotations (i : ZMod n) :
    DihedralGroup.sr i ∉ dihedralRotations n := fun h => by
  obtain ⟨j, hj⟩ := mem_dihedralRotations_iff.mp h
  simp at hj

/-- The rotation subgroup has index `2`. -/
@[simp]
theorem index_dihedralRotations (n : ℕ) : (dihedralRotations n).index = 2 := by
  rw [dihedralRotations, Subgroup.index_ker,
    MonoidHom.range_eq_top.mpr (dihedralReflectionParity_surjective n)]
  simp

/-- The rotation subgroup has finite index, for every `n` -- including `n = 0`, where
`DihedralGroup n` is infinite. -/
instance finiteIndex_dihedralRotations (n : ℕ) : (dihedralRotations n).FiniteIndex :=
  ⟨by simp⟩

/-- **The rotation subgroup has `n` elements**: it has index `2` in a group of order `2 * n`. For
`n = 0` both sides are the junk value `0` that `Nat.card` takes on an infinite group.

Not a `simp` lemma: `TauCeti.mem_dihedralRotations_iff` rewrites the membership predicate inside
the coercion, so the left-hand side here is not in `simp`-normal form. -/
theorem card_dihedralRotations (n : ℕ) : Nat.card (dihedralRotations n) = n := by
  have h := (dihedralRotations n).card_mul_index
  rw [index_dihedralRotations, DihedralGroup.nat_card] at h
  omega

/-- **Conjugation by a reflection inverts every rotation.** This is the defining dihedral relation
`s r s⁻¹ = r⁻¹`, stated for the subgroup rather than for a chosen generator; it is what makes the
conjugate of a linear character of the rotation subgroup its inverse. -/
theorem conj_eq_inv_of_notMem_dihedralRotations {s g : DihedralGroup n}
    (hs : s ∉ dihedralRotations n) (hg : g ∈ dihedralRotations n) : s * g * s⁻¹ = g⁻¹ := by
  obtain ⟨i, rfl⟩ := mem_dihedralRotations_iff.mp hg
  cases s with
  | r j => exact absurd (r_mem_dihedralRotations j) hs
  | sr j =>
    rw [DihedralGroup.inv_sr, DihedralGroup.sr_mul_r, DihedralGroup.sr_mul_sr,
      DihedralGroup.inv_r]
    exact congrArg DihedralGroup.r (by ring)

/-- **Conjugation by a reflection inverts every rotation, inside the rotation subgroup**: this is
`TauCeti.conj_eq_inv_of_notMem_dihedralRotations` read as an equality in `dihedralRotations n`,
where the conjugation action of the ambient group on a normal subgroup lives. -/
@[simp]
theorem conjNormal_eq_inv_of_notMem_dihedralRotations {s : DihedralGroup n}
    (hs : s ∉ dihedralRotations n) (x : dihedralRotations n) :
    MulAut.conjNormal s x = x⁻¹ :=
  Subtype.ext (by
    rw [MulAut.conjNormal_apply]
    simpa using conj_eq_inv_of_notMem_dihedralRotations hs x.2)

/-- The **rotation index** of a dihedral element: the index `i` of a rotation `r i`, and the junk
value `0` on a reflection. This is the ambient pattern match only; the interface is
`TauCeti.dihedralRotationsMulEquiv`, which reads the index off an element of the rotation subgroup
and so never meets the junk value. -/
private def dihedralRotationIndex {n : ℕ} : DihedralGroup n → ZMod n
  | DihedralGroup.r i => i
  | DihedralGroup.sr _ => 0

/-- On the rotation subgroup the rotation index is a section of `r`. -/
private theorem r_dihedralRotationIndex {g : DihedralGroup n} (hg : g ∈ dihedralRotations n) :
    DihedralGroup.r (dihedralRotationIndex g) = g := by
  obtain ⟨i, rfl⟩ := mem_dihedralRotations_iff.mp hg
  rfl

/-- On the rotation subgroup the rotation index is additive. -/
private theorem dihedralRotationIndex_mul {g h : DihedralGroup n} (hg : g ∈ dihedralRotations n)
    (hh : h ∈ dihedralRotations n) :
    dihedralRotationIndex (g * h) = dihedralRotationIndex g + dihedralRotationIndex h := by
  obtain ⟨i, rfl⟩ := mem_dihedralRotations_iff.mp hg
  obtain ⟨j, rfl⟩ := mem_dihedralRotations_iff.mp hh
  rw [DihedralGroup.r_mul_r]
  rfl

/-- **The rotation subgroup is `ZMod n` written multiplicatively**: the rotation `r i` has
coordinate `i`. This is the canonical coordinate on `TauCeti.dihedralRotations`, and it is what
lets a character of the rotation subgroup be named by a single `n`-th root of unity. -/
def dihedralRotationsMulEquiv (n : ℕ) : dihedralRotations n ≃* Multiplicative (ZMod n) where
  toFun x := Multiplicative.ofAdd (dihedralRotationIndex (x : DihedralGroup n))
  invFun i := ⟨DihedralGroup.r (Multiplicative.toAdd i), r_mem_dihedralRotations _⟩
  left_inv x := Subtype.ext (r_dihedralRotationIndex x.2)
  right_inv _ := rfl
  map_mul' x y := congrArg Multiplicative.ofAdd (dihedralRotationIndex_mul x.2 y.2)

@[simp]
theorem dihedralRotationsMulEquiv_r (i : ZMod n) :
    dihedralRotationsMulEquiv n ⟨DihedralGroup.r i, r_mem_dihedralRotations i⟩ =
      Multiplicative.ofAdd i :=
  (rfl)

@[simp]
theorem coe_dihedralRotationsMulEquiv_symm (i : Multiplicative (ZMod n)) :
    ((dihedralRotationsMulEquiv n).symm i : DihedralGroup n) =
      DihedralGroup.r (Multiplicative.toAdd i) :=
  (rfl)

/-- The rotation subgroup is cyclic, `Multiplicative (ZMod n)` being so; in particular it is
commutative. -/
instance isCyclic_dihedralRotations (n : ℕ) : IsCyclic (dihedralRotations n) :=
  isCyclic_of_surjective _ (dihedralRotationsMulEquiv n).symm.surjective

end Rotations

/-! ### The subgroup generated by a reflection -/

section Reflection

variable {n : ℕ}

/-- A reflection is not the identity. -/
@[simp]
theorem dihedralSr_ne_one (i : ZMod n) : DihedralGroup.sr i ≠ 1 := fun h =>
  sr_notMem_dihedralRotations i (by rw [h]; exact one_mem _)

/-- **The subgroup generated by a reflection is `{1, sr i}`.** -/
@[simp]
theorem mem_zpowers_dihedralSr_iff {i : ZMod n} {g : DihedralGroup n} :
    g ∈ Subgroup.zpowers (DihedralGroup.sr i) ↔ g = 1 ∨ g = DihedralGroup.sr i :=
  Subgroup.mem_zpowers_iff_of_orderOf_eq_two (DihedralGroup.orderOf_sr i)

/-- The subgroup generated by a reflection is proper, except in `DihedralGroup 1`, the group of
order two that a single reflection exhausts. -/
theorem zpowers_dihedralSr_ne_top (hn : n ≠ 1) (i : ZMod n) :
    Subgroup.zpowers (DihedralGroup.sr i) ≠ ⊤ := by
  intro htop
  have h := Subgroup.card_top (G := DihedralGroup n)
  rw [← htop, Nat.card_zpowers, DihedralGroup.orderOf_sr, DihedralGroup.nat_card] at h
  omega

/-- A rotation lying in the subgroup generated by a reflection is the identity: the two subgroups
meet only there. -/
theorem eq_one_of_mem_dihedralRotations_of_mem_zpowers_sr {i : ZMod n} {g : DihedralGroup n}
    (hg : g ∈ dihedralRotations n) (hgs : g ∈ Subgroup.zpowers (DihedralGroup.sr i)) : g = 1 := by
  rcases mem_zpowers_dihedralSr_iff.mp hgs with h | h
  · exact h
  · exact absurd (h ▸ hg) (sr_notMem_dihedralRotations i)

/-- **The rotation subgroup and a reflection subgroup are complementary at every degree**, so
`DihedralGroup n = C_n ⋊ C₂`. This holds for every `n`, including `n = 0`, where it presents the
infinite dihedral group as `ℤ ⋊ C₂`. -/
theorem isComplement'_dihedralRotations_zpowers_sr (i : ZMod n) :
    (dihedralRotations n).IsComplement' (Subgroup.zpowers (DihedralGroup.sr i)) := by
  refine Subgroup.isComplement'_of_disjoint_and_mul_eq_univ
    (Subgroup.disjoint_def.2 fun hg hgs =>
      eq_one_of_mem_dihedralRotations_of_mem_zpowers_sr hg hgs)
    (Set.eq_univ_of_forall fun g => Set.mem_mul.2 ?_)
  rcases g with j | m
  · exact ⟨DihedralGroup.r j, r_mem_dihedralRotations j, 1, one_mem _, mul_one _⟩
  · exact ⟨DihedralGroup.r (i - m), r_mem_dihedralRotations _, DihedralGroup.sr i,
      Subgroup.mem_zpowers _, by rw [DihedralGroup.r_mul_sr, sub_sub_cancel]⟩

end Reflection

end TauCeti
