/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.DirectSum.Module
public import TauCeti.Geometry.Hodge.Structure

/-!
# The Hodge decomposition

This file proves the equivalence, due to Deligne, between the two descriptions of a pure Hodge
structure: an `n`-opposed bounded filtration on one side, and a `(p,q)`-decomposition on the other.

In the forward direction the Hodge components of a pure Hodge structure form an internal direct
sum: every step of the decreasing Hodge filtration is recovered as the supremum of the components
in that step, and the full family of components is independent.

In the backward direction a family of subspaces that decomposes the space, is exchanged by the
conjugation in complementary bidegrees, and is bounded below is packaged as
`TauCeti.Hodge.IsHodgeDecomposition`, and the filtration `F^p = ⨆_{q ≥ p} H^q` it generates is a
pure Hodge structure whose components are the given family. The two constructions are mutually
inverse, which is `TauCeti.Hodge.HodgeStructureOn.decompositionEquiv`.

The key local calculation uses two adjacent opposedness decompositions. The component
`H^{p,n-p}` is complementary to the sum of the conjugate step below it and the filtration step
above it. Consequently every other component lies in this explicit complement. Boundedness then
turns the one-step identity `F p = H^{p,n-p} ⊔ F (p + 1)` into filtration recovery by descending
induction.

This is the opposed-filtration description of the Hodge decomposition in Deligne, *Théorie de
Hodge II*, §1.2.1, and Voisin, *Hodge Theory and Complex Algebraic Geometry I*, §6.

## Main declarations

* `TauCeti.Hodge.HodgeStructureOn.F_eq_iSup_piece`: a filtration step is the supremum of the
  Hodge components it contains.
* `TauCeti.Hodge.HodgeStructureOn.conjF_eq_iSup_piece`: a conjugate filtration step is the
  supremum of the Hodge components it contains.
* `TauCeti.Hodge.HodgeStructureOn.piece_iSupIndep`: the Hodge components are independent.
* `TauCeti.Hodge.HodgeStructureOn.isInternal_piece`: the Hodge components form an internal direct
  sum of the ambient complex vector space.
* `TauCeti.Hodge.HodgeStructureOn.decomposition`: that direct sum as a linear equivalence.
* `TauCeti.Hodge.HodgeStructureOn.piece_induction_on`: induction along the Hodge decomposition.
* `TauCeti.Hodge.HodgeStructureOn.proj`: the projection onto a Hodge component along that
  decomposition.
* `TauCeti.Hodge.HodgeStructureOn.proj_mem_F` and
  `TauCeti.Hodge.HodgeStructureOn.proj_eq_zero_of_mem_F_of_lt`: the projections of a vector of
  `F p` stay in `F p` and vanish below degree `p`.
* `TauCeti.Hodge.HodgeStructureOn.sum_proj_eq`: the projections in the finitely many degrees
  carrying a nonzero component sum to the identity.
* `TauCeti.Hodge.IsHodgeDecomposition`: a bounded below, conjugation-symmetric internal direct sum
  decomposition of the ambient complex vector space.
* `TauCeti.Hodge.HodgeStructureOn.ofDecomposition`: the pure Hodge structure generated by a Hodge
  decomposition, with `TauCeti.Hodge.HodgeStructureOn.ofDecomposition_piece` recovering the
  decomposition from it.
* `TauCeti.Hodge.HodgeStructureOn.isEffective_iff_piece_ne_bot`: a pure Hodge structure of weight
  `n` is effective exactly when its nonzero Hodge components `H^{p,n-p}` have `0 ≤ p ≤ n`.
* `TauCeti.Hodge.HodgeStructureOn.piece_injective`: a pure Hodge structure is determined by its
  Hodge components.
* `TauCeti.Hodge.HodgeStructureOn.decompositionEquiv`: pure Hodge structures of weight `n` and
  Hodge decompositions of weight `n` are the same thing.
-/

public section

namespace TauCeti.Hodge

open scoped DirectSum

universe u

namespace HodgeStructureOn

variable {W : Type u} [AddCommGroup W] [Module ℂ W]
variable {ω : Conjugation W} {n : ℤ}

/-- A filtration step is the sum of its Hodge component and the next filtration step. -/
theorem F_eq_piece_sup_succ (hs : HodgeStructureOn W ω n) (p : ℤ) :
    hs.F p = hs.piece p ⊔ hs.F (p + 1) := by
  have hnext : IsCompl (hs.F (p + 1)) (hs.conjF (n - p)) := by
    have hindex : n + 1 - (p + 1) = n - p := by omega
    simpa only [hindex] using hs.isCompl_F_conjF (p + 1)
  have hle : hs.F (p + 1) ≤ hs.F p := hs.F_antitone (by omega)
  calc
    hs.F p = ⊤ ⊓ hs.F p := (top_inf_eq _).symm
    _ = (hs.F (p + 1) ⊔ hs.conjF (n - p)) ⊓ hs.F p := by rw [hnext.sup_eq_top]
    _ = hs.F (p + 1) ⊔ hs.conjF (n - p) ⊓ hs.F p :=
      sup_inf_assoc_of_le _ hle
    _ = hs.piece p ⊔ hs.F (p + 1) := by
      rw [hs.piece_def, inf_comm, sup_comm]

/-- The `p`-th Hodge component is complementary to the sum of the adjacent conjugate and ordinary
filtration steps. This complement contains every Hodge component of degree different from `p`. -/
theorem isCompl_piece_conjF_sup_F (hs : HodgeStructureOn W ω n) (p : ℤ) :
    IsCompl (hs.piece p) (hs.conjF (n + 1 - p) ⊔ hs.F (p + 1)) := by
  have hnext : IsCompl (hs.F (p + 1)) (hs.conjF (n - p)) := by
    have hindex : n + 1 - (p + 1) = n - p := by omega
    simpa only [hindex] using hs.isCompl_F_conjF (p + 1)
  have hdisjoint : Disjoint (hs.piece p) (hs.F (p + 1)) :=
    (hnext.disjoint.mono_right (hs.piece_le_conjF p)).symm
  have hcomp : IsCompl (hs.piece p ⊔ hs.F (p + 1)) (hs.conjF (n + 1 - p)) := by
    rw [← hs.F_eq_piece_sup_succ p]
    exact hs.isCompl_F_conjF p
  simpa only [sup_comm] using hdisjoint.isCompl_sup_right_of_isCompl_sup_left hcomp

/-- Every Hodge component whose degree is smaller than `p` lies in the conjugate filtration step
complementary to `F p`. -/
theorem piece_le_conjF_of_lt (hs : HodgeStructureOn W ω n) {p q : ℤ} (hqp : q < p) :
    hs.piece q ≤ hs.conjF (n + 1 - p) :=
  (hs.piece_le_conjF q).trans (hs.conjF_antitone (by omega))

/-- Every Hodge component whose degree is larger than `p` lies in the filtration step
complementary to `conjF (n - p)`. -/
theorem piece_le_F_succ_of_lt (hs : HodgeStructureOn W ω n) {p q : ℤ} (hpq : p < q) :
    hs.piece q ≤ hs.F (p + 1) :=
  (hs.piece_le_F q).trans (hs.F_antitone (by omega))

/-- The Hodge components of an opposed filtration are independent. -/
theorem piece_iSupIndep (hs : HodgeStructureOn W ω n) : iSupIndep hs.piece := by
  intro p
  refine (hs.isCompl_piece_conjF_sup_F p).disjoint.mono_right ?_
  refine iSup_le fun q ↦ iSup_le fun hqp ↦ ?_
  obtain hqp | hpq := lt_or_gt_of_ne hqp
  · exact (hs.piece_le_conjF_of_lt hqp).trans le_sup_left
  · exact (hs.piece_le_F_succ_of_lt hpq).trans le_sup_right

/-- Every Hodge filtration step is the supremum of the Hodge components in at least that degree:
`F p = ⨆ q ≥ p, H^{q,n-q}`. -/
theorem F_eq_iSup_piece (hs : HodgeStructureOn W ω n) (p : ℤ) :
    hs.F p = ⨆ q, ⨆ (_ : p ≤ q), hs.piece q := by
  apply le_antisymm
  · obtain ⟨b, hb⟩ := hs.F_bot
    let c := max p b
    have hpc : p ≤ c := le_max_left _ _
    have hc : hs.F c = ⊥ := hs.F_eq_bot_of_le hb (le_max_right _ _)
    exact Int.leInductionDown (m := c)
      (motive := fun q _ ↦ hs.F q ≤ ⨆ r, ⨆ (_ : q ≤ r), hs.piece r)
      (by rw [hc]; exact bot_le)
      (fun q _ hq ↦ by
        rw [hs.F_eq_piece_sup_succ (q - 1)]
        refine sup_le (le_iSup₂_of_le (q - 1) le_rfl le_rfl) ?_
        have htail : (⨆ r, ⨆ (_ : q ≤ r), hs.piece r) ≤
            ⨆ r, ⨆ (_ : q - 1 ≤ r), hs.piece r := by
          exact iSup₂_le fun r hqr ↦ le_iSup₂_of_le r (by omega) le_rfl
        simpa only [sub_add_cancel] using hq.trans htail)
      p hpc
  · refine iSup_le fun q ↦ iSup_le fun hpq ↦ ?_
    exact (hs.piece_le_F q).trans (hs.F_antitone hpq)

/-- Every conjugate Hodge filtration step is the supremum of the Hodge components in at most the
complementary degree: `conjF p = ⨆ q ≤ n - p, H^{q,n-q}`. -/
theorem conjF_eq_iSup_piece (hs : HodgeStructureOn W ω n) (p : ℤ) :
    hs.conjF p = ⨆ q, ⨆ (_ : q ≤ n - p), hs.piece q := by
  rw [hs.conjF_def, hs.F_eq_iSup_piece p]
  simp only [Submodule.map_iSup, hs.conj_piece]
  refine le_antisymm (iSup₂_le fun q _ ↦ le_iSup₂_of_le (n - q) (by omega) le_rfl)
    (iSup₂_le fun q _ ↦ le_iSup₂_of_le (n - q) (by omega) (le_of_eq (by rw [sub_sub_cancel])))

/-- The supremum of all Hodge components is the whole ambient complex vector space. -/
theorem iSup_piece_eq_top (hs : HodgeStructureOn W ω n) : ⨆ p, hs.piece p = ⊤ := by
  obtain ⟨p, hp⟩ := hs.F_top
  apply top_unique
  rw [← hp, hs.F_eq_iSup_piece p]
  exact iSup₂_le fun q _ ↦ le_iSup hs.piece q

/-- **The Hodge decomposition.** The Hodge components `H^{p,n-p}` form an internal direct sum of
the ambient complex vector space. -/
theorem isInternal_piece (hs : HodgeStructureOn W ω n) : DirectSum.IsInternal hs.piece := by
  classical
  exact DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top
    hs.piece_iSupIndep hs.iSup_piece_eq_top

/-- The Hodge decomposition as a linear equivalence: the ambient complex vector space is the
direct sum of its Hodge components. -/
noncomputable def decomposition (hs : HodgeStructureOn W ω n) :
    W ≃ₗ[ℂ] ⨁ p, hs.piece p :=
  (LinearEquiv.ofBijective (DirectSum.coeLinearMap hs.piece) hs.isInternal_piece).symm

/-- The inverse of the Hodge decomposition sums up the Hodge components. -/
@[simp]
theorem decomposition_symm_apply (hs : HodgeStructureOn W ω n) (x : ⨁ p, hs.piece p) :
    hs.decomposition.symm x = DirectSum.coeLinearMap hs.piece x := by
  rw [decomposition, LinearEquiv.symm_symm]
  rfl

/-- A vector lying in a single Hodge component decomposes as that one component. -/
theorem decomposition_apply_of_mem (hs : HodgeStructureOn W ω n) {p : ℤ} {x : W}
    (hx : x ∈ hs.piece p) :
    hs.decomposition x = DirectSum.lof ℂ ℤ (fun q ↦ hs.piece q) p ⟨x, hx⟩ :=
  hs.decomposition.symm.injective (by simp)

/-- Induction along the Hodge decomposition: a property that holds at zero, is stable under
addition, and holds on every Hodge component holds everywhere. -/
theorem piece_induction_on (hs : HodgeStructureOn W ω n) {motive : W → Prop} (x : W)
    (mem : ∀ p, ∀ y ∈ hs.piece p, motive y) (zero : motive 0)
    (add : ∀ y z, motive y → motive z → motive (y + z)) : motive x := by
  have hx : x ∈ ⨆ p, hs.piece p := by
    rw [hs.iSup_piece_eq_top]
    exact Submodule.mem_top
  exact Submodule.iSup_induction (motive := motive) hs.piece hx mem zero add

/-- Two complex-linear maps out of the ambient space that agree on every Hodge component are
equal. -/
theorem linearMap_ext_of_piece {N : Type*} [AddCommMonoid N] [Module ℂ N]
    (hs : HodgeStructureOn W ω n) {f g : W →ₗ[ℂ] N}
    (h : ∀ p, ∀ x ∈ hs.piece p, f x = g x) : f = g := by
  ext x
  refine hs.piece_induction_on x h (by simp) fun y z hy hz ↦ ?_
  rw [map_add, map_add, hy, hz]

/-! ### The Hodge projections -/

/-- The projection of the ambient complex vector space onto the Hodge component `H^{p, n-p}`
along the Hodge decomposition. -/
noncomputable def proj (hs : HodgeStructureOn W ω n) (p : ℤ) : W →ₗ[ℂ] W :=
  (hs.piece p).subtype ∘ₗ DirectSum.component ℂ ℤ (fun q ↦ hs.piece q) p ∘ₗ
    hs.decomposition.toLinearMap

theorem proj_apply (hs : HodgeStructureOn W ω n) (p : ℤ) (x : W) :
    hs.proj p x = (hs.decomposition x p : W) :=
  (rfl)

/-- A Hodge projection lands in the corresponding Hodge component. -/
theorem proj_mem (hs : HodgeStructureOn W ω n) (p : ℤ) (x : W) : hs.proj p x ∈ hs.piece p := by
  rw [proj_apply]
  exact (hs.decomposition x p).2

/-- The Hodge projection of degree `p` fixes the Hodge component of degree `p`. -/
@[simp]
theorem proj_apply_of_mem (hs : HodgeStructureOn W ω n) {p : ℤ} {x : W} (hx : x ∈ hs.piece p) :
    hs.proj p x = x := by
  rw [proj_apply, hs.decomposition_apply_of_mem hx]
  simp

/-- The Hodge projection of degree `p` annihilates every other Hodge component. -/
theorem proj_apply_eq_zero_of_mem_of_ne (hs : HodgeStructureOn W ω n) {p q : ℤ} {x : W}
    (hx : x ∈ hs.piece q) (hqp : q ≠ p) : hs.proj p x = 0 := by
  rw [proj_apply, hs.decomposition_apply_of_mem hx, DirectSum.lof_eq_of,
    DirectSum.of_eq_of_ne _ _ _ hqp.symm]
  rfl

/-- The Hodge projections in the degrees of a finite set carrying every nonzero Hodge component
sum to the identity: a vector is the sum of its finitely many Hodge components. -/
theorem sum_proj_eq (hs : HodgeStructureOn W ω n) {S : Finset ℤ}
    (hS : ∀ p ∉ S, hs.piece p = ⊥) (x : W) : ∑ p ∈ S, hs.proj p x = x := by
  refine hs.piece_induction_on (motive := fun y ↦ ∑ p ∈ S, hs.proj p y = y) x
    (fun q y hy ↦ ?_) (by simp) (fun y z hy hz ↦ ?_)
  · by_cases hq : q ∈ S
    · rw [Finset.sum_eq_single_of_mem q hq fun b _ hbq ↦
        hs.proj_apply_eq_zero_of_mem_of_ne hy (Ne.symm hbq), hs.proj_apply_of_mem hy]
    · rw [hS q hq] at hy
      rw [(Submodule.mem_bot ℂ).1 hy]
      simp
  · simp only [map_add, Finset.sum_add_distrib, hy, hz]

/-- A vector all of whose Hodge projections vanish is zero. -/
theorem eq_zero_of_proj_eq_zero (hs : HodgeStructureOn W ω n) {x : W}
    (h : ∀ p, hs.proj p x = 0) : x = 0 := by
  refine hs.decomposition.injective ?_
  rw [map_zero]
  ext p
  exact congrArg Subtype.val (Subtype.ext (h p) : hs.decomposition x p = 0)

/-- A vector lies in a supremum of submodules as soon as each of its Hodge projections does. -/
theorem mem_iSup_of_proj_mem (hs : HodgeStructureOn W ω n) {S : ℤ → Submodule ℂ W} {x : W}
    (h : ∀ p, hs.proj p x ∈ S p) : x ∈ ⨆ p, S p := by
  classical
  have hx : x = ∑ p ∈ (hs.decomposition x).support, hs.proj p x := by
    conv_lhs => rw [← hs.decomposition.symm_apply_apply x]
    rw [decomposition_symm_apply, DirectSum.coeLinearMap_eq_dfinsuppSum]
    rw [DFinsupp.sum]
    simp only [proj_apply]
  rw [hx]
  exact Submodule.sum_mem _ fun p _ ↦ Submodule.mem_iSup_of_mem p (h p)

/-- A submodule spanned by its intersections with the Hodge components contains the Hodge
projections of each of its vectors. -/
theorem proj_mem_of_le_iSup_inf (hs : HodgeStructureOn W ω n) {S : Submodule ℂ W}
    (hS : S ≤ ⨆ p, S ⊓ hs.piece p) {x : W} (hx : x ∈ S) (p : ℤ) : hs.proj p x ∈ S := by
  refine Submodule.iSup_induction (motive := fun y ↦ ∀ q, hs.proj q y ∈ S) _ (hS hx)
    (fun q y hy r ↦ ?_) (fun q ↦ by simp) (fun y z hy hz q ↦ ?_) p
  · rcases eq_or_ne q r with rfl | hqr
    · rw [hs.proj_apply_of_mem hy.2]
      exact hy.1
    · rw [hs.proj_apply_eq_zero_of_mem_of_ne hy.2 hqr]
      exact S.zero_mem
  · rw [map_add]
    exact S.add_mem (hy q) (hz q)

/-- A vector lies in a submodule as soon as every one of its Hodge projections does. -/
theorem mem_of_proj_mem (hs : HodgeStructureOn W ω n) {S : Submodule ℂ W} {x : W}
    (h : ∀ p, hs.proj p x ∈ S) : x ∈ S := by
  simpa only [iSup_const] using hs.mem_iSup_of_proj_mem (S := fun _ ↦ S) h

/-- A Hodge component is disjoint from every strictly later filtration step. -/
theorem disjoint_piece_F_of_lt (hs : HodgeStructureOn W ω n) {p q : ℤ} (hpq : p < q) :
    Disjoint (hs.piece p) (hs.F q) :=
  (hs.isCompl_piece_conjF_sup_F p).disjoint.mono_right
    ((hs.F_antitone (by omega : p + 1 ≤ q)).trans le_sup_right)

/-- A filtration step is spanned by its intersections with the Hodge components. -/
theorem F_le_iSup_inf_piece (hs : HodgeStructureOn W ω n) (p : ℤ) :
    hs.F p ≤ ⨆ q, hs.F p ⊓ hs.piece q := by
  conv_lhs => rw [hs.F_eq_iSup_piece p]
  refine iSup₂_le fun q hq ↦ le_iSup_of_le q (le_inf ?_ le_rfl)
  exact (hs.piece_le_F q).trans (hs.F_antitone hq)

/-- The Hodge projections of a vector of a filtration step stay in that step. -/
theorem proj_mem_F (hs : HodgeStructureOn W ω n) {p : ℤ} {x : W} (hx : x ∈ hs.F p) (q : ℤ) :
    hs.proj q x ∈ hs.F p :=
  hs.proj_mem_of_le_iSup_inf (hs.F_le_iSup_inf_piece p) hx q

/-- The Hodge projections of a vector of `F p` vanish in every degree below `p`. -/
theorem proj_eq_zero_of_mem_F_of_lt (hs : HodgeStructureOn W ω n) {p q : ℤ} {x : W}
    (hx : x ∈ hs.F p) (hqp : q < p) : hs.proj q x = 0 := by
  have hmem : hs.proj q x ∈ hs.piece q ⊓ hs.F p :=
    Submodule.mem_inf.2 ⟨hs.proj_mem q x, hs.proj_mem_F hx q⟩
  rw [disjoint_iff.mp (hs.disjoint_piece_F_of_lt hqp)] at hmem
  simpa using hmem

end HodgeStructureOn

/-! ### Reconstructing a Hodge structure from its decomposition

The Hodge decomposition above is more than a consequence of opposedness: the two descriptions of a
pure Hodge structure carry the same information. The rest of this file runs the equivalence
backwards, generating an opposed filtration from a family of components and identifying the two
constructions in both directions.
-/

/-- A **Hodge decomposition** of weight `n` on a complex vector space with conjugation `ω`: a
family `H` of subspaces that decomposes the space as an internal direct sum, is exchanged by the
conjugation in complementary bidegrees, and vanishes in all sufficiently small degrees.

This is the data on the other side of Deligne's equivalence. The Hodge components of a pure Hodge
structure form such a family, by `TauCeti.Hodge.HodgeStructureOn.isHodgeDecomposition_piece`, and
every such family arises this way from exactly one Hodge structure, by
`TauCeti.Hodge.HodgeStructureOn.decompositionEquiv`. -/
structure IsHodgeDecomposition {W : Type u} [AddCommGroup W] [Module ℂ W]
    (ω : Conjugation W) (n : ℤ) (H : ℤ → Submodule ℂ W) : Prop where
  /-- The components form an internal direct sum of the ambient complex vector space. -/
  isInternal : DirectSum.IsInternal H
  /-- Conjugation exchanges the components of complementary bidegrees. -/
  map_conj : ∀ p, (H p).map ω.toEquiv.toLinearMap = H (n - p)
  /-- The decomposition is bounded below: its components vanish in all sufficiently small degrees.
  Boundedness above is then automatic, by
  `TauCeti.Hodge.IsHodgeDecomposition.exists_forall_gt_eq_bot`. -/
  exists_forall_lt_eq_bot : ∃ a, ∀ p < a, H p = ⊥

namespace IsHodgeDecomposition

variable {W : Type u} [AddCommGroup W] [Module ℂ W]
variable {ω : Conjugation W} {n : ℤ} {H : ℤ → Submodule ℂ W}

/-- The components of a Hodge decomposition are independent. -/
theorem iSupIndep (h : IsHodgeDecomposition ω n H) : _root_.iSupIndep H :=
  h.isInternal.submodule_iSupIndep

/-- The components of a Hodge decomposition span the ambient complex vector space. -/
theorem iSup_eq_top (h : IsHodgeDecomposition ω n H) : ⨆ p, H p = ⊤ :=
  h.isInternal.submodule_iSup_eq_top

/-- Elementwise form of the exchange of the components of a Hodge decomposition by
conjugation. -/
theorem conj_mem (h : IsHodgeDecomposition ω n H) {p : ℤ} {x : W} (hx : x ∈ H p) :
    ω.toEquiv x ∈ H (n - p) :=
  h.map_conj p ▸ Submodule.mem_map_of_mem hx

/-- A Hodge decomposition is bounded above as well: its components vanish in all sufficiently
large degrees. This is the mirror image of boundedness below under the conjugation symmetry. -/
theorem exists_forall_gt_eq_bot (h : IsHodgeDecomposition ω n H) :
    ∃ b, ∀ p, b < p → H p = ⊥ := by
  obtain ⟨a, ha⟩ := h.exists_forall_lt_eq_bot
  refine ⟨n - a, fun p hp ↦ ?_⟩
  have hmap := ω.map_map_eq_self (H p)
  rw [h.map_conj p, ha _ (by omega), Submodule.map_bot] at hmap
  exact hmap.symm

/-- Only finitely many components of a Hodge decomposition are nonzero. -/
theorem finite_setOf_ne_bot (h : IsHodgeDecomposition ω n H) : {p | H p ≠ ⊥}.Finite := by
  obtain ⟨a, ha⟩ := h.exists_forall_lt_eq_bot
  obtain ⟨b, hb⟩ := h.exists_forall_gt_eq_bot
  refine (Set.finite_Icc a b).subset fun p hp ↦ Set.mem_Icc.2 ⟨?_, ?_⟩
  · by_contra hpa
    exact hp (ha p (by omega))
  · by_contra hpb
    exact hp (hb p (by omega))

/-- Beyond a degree below which all components of a Hodge decomposition vanish, the tail sum
`⨆_{q ≥ a} H^q` is already the whole space. -/
theorem iSup_ge_eq_top (h : IsHodgeDecomposition ω n H) {a : ℤ} (ha : ∀ p < a, H p = ⊥) :
    ⨆ q, ⨆ (_ : a ≤ q), H q = ⊤ := by
  refine top_unique ?_
  rw [← h.iSup_eq_top]
  refine iSup_le fun q ↦ ?_
  rcases le_or_gt a q with hq | hq
  · exact le_iSup₂_of_le q hq le_rfl
  · rw [ha q hq]
    exact bot_le

/-- Conjugation carries the tail sum `⨆_{q ≥ p} H^q` of a Hodge decomposition onto the head sum
`⨆_{q < n + 1 - p} H^q`. -/
theorem map_iSup_ge (h : IsHodgeDecomposition ω n H) (p : ℤ) :
    (⨆ q, ⨆ (_ : p ≤ q), H q).map ω.toEquiv.toLinearMap =
      ⨆ q, ⨆ (_ : q < n + 1 - p), H q := by
  simp only [Submodule.map_iSup, h.map_conj]
  refine le_antisymm (iSup₂_le fun q _ ↦ le_iSup₂_of_le (n - q) (by omega) le_rfl)
    (iSup₂_le fun q _ ↦ le_iSup₂_of_le (n - q) (by omega) (le_of_eq (by rw [sub_sub_cancel])))

/-- The tail sum `⨆_{q ≥ p} H^q` and the head sum `⨆_{q < p} H^q` of a Hodge decomposition are
disjoint, because the components are independent. -/
theorem disjoint_iSup_ge_iSup_lt (h : IsHodgeDecomposition ω n H) (p : ℤ) :
    Disjoint (⨆ q, ⨆ (_ : p ≤ q), H q) (⨆ q, ⨆ (_ : q < p), H q) := by
  have hdisjoint : Disjoint {q : ℤ | p ≤ q} {q : ℤ | q < p} := by
    rw [Set.disjoint_left]
    intro q hq hq'
    simp only [Set.mem_ofPred_eq] at hq hq'
    omega
  exact h.iSupIndep.disjoint_biSup_biSup hdisjoint

/-- The tail sum `⨆_{q ≥ p} H^q` and the head sum `⨆_{q < p} H^q` of a Hodge decomposition are
complementary: this is the opposedness of the filtration the decomposition generates. -/
theorem isCompl_iSup_ge_iSup_lt (h : IsHodgeDecomposition ω n H) (p : ℤ) :
    IsCompl (⨆ q, ⨆ (_ : p ≤ q), H q) (⨆ q, ⨆ (_ : q < p), H q) := by
  refine ⟨h.disjoint_iSup_ge_iSup_lt p, codisjoint_iff.2 (top_unique ?_)⟩
  rw [← h.iSup_eq_top]
  refine iSup_le fun q ↦ ?_
  rcases le_or_gt p q with hq | hq
  · exact le_sup_of_le_left (le_iSup₂_of_le q hq le_rfl)
  · exact le_sup_of_le_right (le_iSup₂_of_le q hq le_rfl)

end IsHodgeDecomposition

namespace HodgeStructureOn

variable {W : Type u} [AddCommGroup W] [Module ℂ W]
variable {ω : Conjugation W} {n : ℤ} {H : ℤ → Submodule ℂ W}

/-- The pure Hodge structure of weight `n` generated by a Hodge decomposition: its filtration step
`F^p` is the sum `⨆_{q ≥ p} H^q` of the components of degree at least `p`.

This is the converse half of Deligne's equivalence between `n`-opposed filtrations and
`(p,q)`-decompositions, `TauCeti.Hodge.HodgeStructureOn.isInternal_piece` being the forward
half. -/
noncomputable def ofDecomposition (h : IsHodgeDecomposition ω n H) : HodgeStructureOn W ω n where
  F p := ⨆ q, ⨆ (_ : p ≤ q), H q
  F_antitone _ _ hpp' := iSup₂_le fun q hq ↦ le_iSup₂_of_le q (hpp'.trans hq) le_rfl
  F_top := by
    obtain ⟨a, ha⟩ := h.exists_forall_lt_eq_bot
    exact ⟨a, h.iSup_ge_eq_top ha⟩
  opposed p := by
    have hindex : n + 1 - (n + 1 - p) = p := by omega
    rw [h.map_iSup_ge, hindex]
    exact h.isCompl_iSup_ge_iSup_lt p

/-- The filtration generated by a Hodge decomposition is the sum of the components of degree at
least the filtration index. -/
@[simp]
theorem ofDecomposition_F (h : IsHodgeDecomposition ω n H) (p : ℤ) :
    (ofDecomposition h).F p = ⨆ q, ⨆ (_ : p ≤ q), H q :=
  (rfl)

/-- The conjugate of the filtration generated by a Hodge decomposition is the sum of the
components of degree below the complementary index. -/
@[simp]
theorem ofDecomposition_conjF (h : IsHodgeDecomposition ω n H) (p : ℤ) :
    (ofDecomposition h).conjF p = ⨆ q, ⨆ (_ : q < n + 1 - p), H q := by
  rw [conjF_def, ofDecomposition_F, h.map_iSup_ge]

/-- **The components are recovered.** The Hodge components of the Hodge structure generated by a
Hodge decomposition are the members of that decomposition. -/
@[simp]
theorem ofDecomposition_piece (h : IsHodgeDecomposition ω n H) (p : ℤ) :
    (ofDecomposition h).piece p = H p := by
  have hle : H p ≤ ⨆ q, ⨆ (_ : p ≤ q), H q := le_iSup₂_of_le p le_rfl le_rfl
  have hsplit : ⨆ q, ⨆ (_ : q < p + 1), H q = H p ⊔ ⨆ q, ⨆ (_ : q < p), H q := by
    refine le_antisymm (iSup₂_le fun q hq ↦ ?_)
      (sup_le (le_iSup₂_of_le p (by omega) le_rfl)
        (iSup₂_le fun q _ ↦ le_iSup₂_of_le q (by omega) le_rfl))
    rcases eq_or_lt_of_le (Int.lt_add_one_iff.1 hq) with rfl | hqp
    · exact le_sup_left
    · exact le_sup_of_le_right (le_iSup₂_of_le q hqp le_rfl)
  have hindex : n + 1 - (n - p) = p + 1 := by omega
  rw [piece_def, ofDecomposition_F, ofDecomposition_conjF,
    hindex, hsplit, inf_comm,
    sup_inf_assoc_of_le _ hle, (h.disjoint_iSup_ge_iSup_lt p).symm.eq_bot, sup_bot_eq]

/-- The Hodge structure generated by a Hodge decomposition is effective exactly when the
decomposition has no components in negative degrees. -/
theorem ofDecomposition_isEffective_iff (h : IsHodgeDecomposition ω n H) :
    (ofDecomposition h).IsEffective ↔ ∀ p < 0, H p = ⊥ := by
  refine ⟨fun heff p hp ↦ ?_, fun hb ↦ ?_⟩
  · rw [← ofDecomposition_piece h p]
    exact heff.piece_eq_bot_of_neg hp
  · rw [isEffective_iff, ofDecomposition_F]
    exact h.iSup_ge_eq_top hb

/-- **The decomposition of a pure Hodge structure.** The Hodge components of a pure Hodge
structure of weight `n` form a Hodge decomposition of weight `n`. -/
theorem isHodgeDecomposition_piece (hs : HodgeStructureOn W ω n) :
    IsHodgeDecomposition ω n hs.piece where
  isInternal := hs.isInternal_piece
  map_conj := hs.conj_piece
  exists_forall_lt_eq_bot := by
    obtain ⟨a, ha⟩ := hs.F_top
    exact ⟨a, fun p hp ↦ hs.piece_eq_bot_of_F_eq_top ha hp⟩

/-- **The filtration is recovered.** Regenerating a pure Hodge structure from its own Hodge
components returns it unchanged. -/
@[simp]
theorem ofDecomposition_isHodgeDecomposition_piece (hs : HodgeStructureOn W ω n) :
    ofDecomposition hs.isHodgeDecomposition_piece = hs := by
  refine HodgeStructureOn.ext (funext fun p ↦ ?_)
  rw [ofDecomposition_F, hs.F_eq_iSup_piece p]

/-- A pure Hodge structure is effective exactly when it has no Hodge components in negative
degrees. -/
theorem isEffective_iff_piece_eq_bot (hs : HodgeStructureOn W ω n) :
    hs.IsEffective ↔ ∀ p < 0, hs.piece p = ⊥ := by
  conv_lhs => rw [← hs.ofDecomposition_isHodgeDecomposition_piece]
  exact ofDecomposition_isEffective_iff hs.isHodgeDecomposition_piece

/-- **Effectivity is a support condition on the Hodge components.** A pure Hodge structure of
weight `n` is effective exactly when each of its nonzero Hodge components `H^{p,n-p}` has
`0 ≤ p ≤ n`. -/
theorem isEffective_iff_piece_ne_bot (hs : HodgeStructureOn W ω n) :
    hs.IsEffective ↔ ∀ p, hs.piece p ≠ ⊥ → p ∈ Set.Icc 0 n := by
  refine ⟨fun h p hp ↦ ⟨not_lt.1 fun hp0 ↦ hp (h.piece_eq_bot_of_neg hp0),
    not_lt.1 fun hpn ↦ hp (h.piece_eq_bot_of_weight_lt hpn)⟩,
    fun h ↦ hs.isEffective_iff_piece_eq_bot.2 fun p hp ↦ ?_⟩
  by_contra hne
  exact not_le.2 hp (h p hne).1

/-- A pure Hodge structure is determined by its Hodge components. -/
theorem piece_injective :
    Function.Injective (piece : HodgeStructureOn W ω n → ℤ → Submodule ℂ W) := by
  intro hs hs' hpiece
  refine HodgeStructureOn.ext (funext fun p ↦ ?_)
  rw [hs.F_eq_iSup_piece p, hs'.F_eq_iSup_piece p, hpiece]

/-- **Deligne's equivalence.** A pure Hodge structure of weight `n` on a complex vector space with
conjugation is the same thing as a Hodge decomposition of weight `n`: the filtration is generated
by the components as `F^p = ⨆_{q ≥ p} H^q`, and the components are cut out of the filtration as
`H^p = F^p ⊓ conj F^{n-p}`. -/
noncomputable def decompositionEquiv (ω : Conjugation W) (n : ℤ) :
    HodgeStructureOn W ω n ≃ {H : ℤ → Submodule ℂ W // IsHodgeDecomposition ω n H} where
  toFun hs := ⟨hs.piece, hs.isHodgeDecomposition_piece⟩
  invFun H := ofDecomposition H.2
  left_inv hs := ofDecomposition_isHodgeDecomposition_piece hs
  right_inv H := Subtype.ext (funext fun p ↦ ofDecomposition_piece H.2 p)

@[simp]
theorem coe_decompositionEquiv_apply (hs : HodgeStructureOn W ω n) :
    (↑(decompositionEquiv ω n hs) : ℤ → Submodule ℂ W) = hs.piece :=
  (rfl)

@[simp]
theorem decompositionEquiv_symm_apply
    (H' : {H : ℤ → Submodule ℂ W // IsHodgeDecomposition ω n H}) :
    (decompositionEquiv ω n).symm H' = ofDecomposition H'.2 :=
  (rfl)

end HodgeStructureOn

end TauCeti.Hodge
