/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Ideal.Maximal
public import Mathlib.RingTheory.Jacobson.Radical
public import Mathlib.RingTheory.Nilpotent.Basic
public import TauCeti.RepresentationTheory.Quiver.Acyclic.FinitePaths
public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.Basic

/-!
# The arrow ideal of a path algebra, and its radical

The path algebra of a quiver is filtered by path length: `pathSpan k Q n` is the `k`-span of the
paths of length at least `n`. Concatenation adds lengths, so the filtration is multiplicative,
`pathSpan k Q m * pathSpan k Q n ⊆ pathSpan k Q (m + n)`, and its first step is a two-sided ideal,
the **arrow ideal** `arrowIdeal k Q`: the elements with no trivial path in their support, that is,
those whose coordinates on the trivial paths all vanish. It is the ideal generated by the arrows,
and its powers are the steps of the filtration: `pathSpan k Q n` is `(arrowIdeal k Q) ^ n`.

For a **finite acyclic** quiver the filtration dies: every path has length strictly less than the
number of vertices, so `pathSpan k Q (Nat.card Q) = ⊥` and every element of the arrow ideal is
nilpotent. This pins the Jacobson radical of the path algebra: it is exactly the arrow ideal
(`TauCeti.jacobson_pathAlgebra_eq_arrowIdeal`). Both inclusions are proved using the finiteness and
the acyclicity, and the equality genuinely needs them: for the one-loop quiver `kQ ≅ k[X]`
(`TauCeti.PathAlgebra.oneLoopAlgEquiv`) has zero radical while its arrow ideal `(X)` is nonzero, so
there the inclusion `arrowIdeal k Q ≤ Ring.jacobson (pathAlgebra k Q)` fails. That example says
nothing about the opposite inclusion, which it satisfies vacuously.

## Main definitions

* `TauCeti.pathSpan k Q n`: the `k`-span of the paths of length at least `n`.
* `TauCeti.arrowIdeal k Q`: the arrow ideal, the ideal of elements supported on the paths of
  positive length, with `TauCeti.arrowIdeal.instIsTwoSided` recording that it is two-sided.

## Main results

* `TauCeti.mul_mem_pathSpan`: the length filtration is multiplicative, and
  `TauCeti.ofPath_mem_pathSpan_iff`: a basis path lies in a step exactly when it is long enough.
* `TauCeti.restrictScalars_arrowIdeal_pow`: **the steps of the length filtration are the powers of
  the arrow ideal**, `TauCeti.mem_arrowIdeal_pow` in terms of membership, and
  `TauCeti.ofPath_mem_arrowIdeal_pow_iff` on a basis path.
* `TauCeti.mem_arrowIdeal_iff_repr_nil`: an element lies in the arrow ideal exactly when all its
  coordinates on the trivial paths vanish, `TauCeti.mem_arrowIdeal_iff` in terms of the lengths of
  the paths in its support, and `TauCeti.ofPath_mem_arrowIdeal_iff` on a basis path.
* `TauCeti.arrowIdeal_eq_span_arrows`: the arrow ideal is the ideal generated by the arrows.
* `TauCeti.pathSpan_eq_bot_of_isAcyclic`: for a finite acyclic quiver the filtration reaches `⊥`
  at the number of vertices, and `TauCeti.isNilpotent_of_mem_arrowIdeal`: every element of the
  arrow ideal is then nilpotent.
* `TauCeti.jacobson_pathAlgebra_eq_arrowIdeal`: **the Jacobson radical of the path algebra of a
  finite acyclic quiver is the arrow ideal.**

## Implementation notes

`pathSpan` is a `k`-submodule rather than an ideal, the multiplicativity statement being about the
`k`-span in any case. *Every* step could be packaged as a two-sided ideal: the `m = 0` and the
`n = 0` cases of multiplicativity, `pathSpan k Q 0` being everything, close `pathSpan k Q n` under
multiplication by the path algebra on either side. Only the first step is packaged separately here,
as `arrowIdeal k Q`, that being the step the radical theorem is about; the higher steps are its
powers, `TauCeti.restrictScalars_arrowIdeal_pow` identifying `pathSpan k Q n` with
`(arrowIdeal k Q) ^ n` as a `k`-submodule, which is the form the radical powers `rad ^ n` and the
admissible ideals `rad ^ N ⊆ I ⊆ rad ^ 2` are stated against.

Membership is described by coordinates for the path basis and on a basis path, at both levels:
`TauCeti.mem_pathSpan_iff` and `TauCeti.mem_arrowIdeal_iff` say that every path carrying a nonzero
coordinate is long enough, which is how the two inclusions of the radical theorem are proved, while
`TauCeti.ofPath_mem_pathSpan_iff` and `TauCeti.ofPath_mem_arrowIdeal_iff` recognize a basis path,
which is how the ideal is recognized in practice. At the level of the arrow ideal the length
condition collapses to the vanishing of the named coordinates on the trivial paths, which is
`TauCeti.mem_arrowIdeal_iff_repr_nil`. The bridge from the arrow ideal to the `pathSpan` it is
implemented by is private: these characterizations, together with
`TauCeti.restrictScalars_arrowIdeal_pow` and `TauCeti.arrowIdeal_eq_span_arrows`, are what consumers
need.

Of these, the basis-path ones are `simp`: their right-hand sides are smaller than their left. The
membership `iff`s whose left-hand side is the bare `f ∈ arrowIdeal k Q` are not, because tagging one
of them would rewrite the left-hand side of `TauCeti.ofPath_mem_arrowIdeal_iff` away, which the
`simpNF` linter rejects.

The arrow ideal is built over a commutative base semiring: the multiplicativity of the filtration,
which is what makes it an ideal, needs `[CommSemiring k]` (see the `Multiplicative` section), and
being an `Ideal` needs the unit of the path algebra, hence `[Finite Q]`. A field is only needed for
the radical theorem, which inverts a coordinate.

## References

This implements the "radical, packaged" part of Layer 3 of
`TauCetiRoadmap/RepresentationTheory/QuiverRepresentations/README.md`, in the case of a path
algebra; the arrow ideal is the ideal that the admissible ideals of that layer are measured
against. See Assem--Simson--Skowroński, *Elements of the Representation Theory of Associative
Algebras I*, Ch. II and III.
-/

public section

namespace TauCeti

open PathAlgebra

universe u v w

section PathSpan

variable (k : Type w) (Q : Type u) [Semiring k] [Quiver.{v} Q]

/-- The `k`-span of the paths of length at least `n`: the `n`-th step of the length filtration of
the path algebra. -/
noncomputable def pathSpan (n : ℕ) : Submodule k (pathAlgebra k Q) :=
  Submodule.span k (pathAlgebraBasis k Q '' {x : Quiver.TotalPath Q | n ≤ x.2.2.length})

variable {k Q}

/-- An element lies in the `n`-th step of the length filtration exactly when every path carrying a
nonzero coordinate has length at least `n`. -/
theorem mem_pathSpan_iff {n : ℕ} {f : pathAlgebra k Q} :
    f ∈ pathSpan k Q n ↔
      ∀ x : Quiver.TotalPath Q, (pathAlgebraBasis k Q).repr f x ≠ 0 → n ≤ x.2.2.length := by
  rw [pathSpan, Module.Basis.mem_span_image]
  simp [Set.subset_def, Finsupp.mem_support_iff]

/-- A path of length at least `n` lies in the `n`-th step of the length filtration. -/
theorem ofPath_mem_pathSpan {n : ℕ} {x : Quiver.TotalPath Q} (hx : n ≤ x.2.2.length) :
    (ofPath x : pathAlgebra k Q) ∈ pathSpan k Q n :=
  Submodule.subset_span ⟨x, hx, by simp⟩

/-- **A basis path lies in the `n`-th step of the length filtration exactly when it has length at
least `n`**: the filtration meets the path basis in the long enough paths. -/
@[simp]
theorem ofPath_mem_pathSpan_iff [Nontrivial k] {n : ℕ} {x : Quiver.TotalPath Q} :
    (ofPath x : pathAlgebra k Q) ∈ pathSpan k Q n ↔ n ≤ x.2.2.length := by
  refine ⟨fun hx => mem_pathSpan_iff.1 hx x ?_, ofPath_mem_pathSpan⟩
  rw [ofPath_eq_single, pathAlgebraBasis_repr_single, Finsupp.single_eq_same]
  exact one_ne_zero

variable (k Q)

/-- The length filtration starts at the whole path algebra. -/
@[simp]
theorem pathSpan_zero : pathSpan k Q 0 = ⊤ := by
  have huniv : {x : Quiver.TotalPath Q | 0 ≤ x.2.2.length} = Set.univ := by
    ext x
    simp
  rw [pathSpan, huniv, Set.image_univ, Module.Basis.span_eq]

variable {k Q}

/-- Everything lies in the zeroth step of the length filtration. -/
theorem mem_pathSpan_zero (f : pathAlgebra k Q) : f ∈ pathSpan k Q 0 := by
  simp

/-- The length filtration is decreasing. -/
theorem pathSpan_le_pathSpan {m n : ℕ} (h : m ≤ n) : pathSpan k Q n ≤ pathSpan k Q m :=
  Submodule.span_mono (Set.image_mono fun _ hx => h.trans hx)

/-- **The length filtration of a finite acyclic quiver dies at the number of vertices**: every path
of a finite acyclic quiver has length strictly less than the number of vertices. -/
theorem pathSpan_eq_bot_of_isAcyclic (k : Type w) (Q : Type u) [Semiring k] [Quiver.{v} Q]
    [Finite Q] (h : Quiver.IsAcyclic Q) : pathSpan k Q (Nat.card Q) = ⊥ := by
  let := Fintype.ofFinite Q
  have hempty : {x : Quiver.TotalPath Q | Nat.card Q ≤ x.2.2.length} = ∅ := by
    ext x
    simp only [Set.mem_ofPred_eq, Set.mem_empty_iff_false, iff_false, Nat.not_le,
      Nat.card_eq_fintype_card]
    exact h.length_lt_card x.2.2
  rw [pathSpan, hempty, Set.image_empty, Submodule.span_empty]

end PathSpan

section Multiplicative

-- The filtration is multiplicative over a commutative base: the proof multiplies through spans on
-- both sides, so it needs both `IsScalarTower` and `SMulCommClass` for `k` on `pathAlgebra k Q`,
-- and the latter is where `[CommSemiring k]` is used. Only powers need the unit, hence
-- `[Finite Q]`.
variable {k : Type w} {Q : Type u} [CommSemiring k] [Quiver.{v} Q]

/-- **The length filtration is multiplicative**: concatenating a path of length at least `m` with
one of length at least `n` gives a path of length at least `m + n`. -/
theorem mul_mem_pathSpan {m n : ℕ} {f g : pathAlgebra k Q} (hf : f ∈ pathSpan k Q m)
    (hg : g ∈ pathSpan k Q n) : f * g ∈ pathSpan k Q (m + n) := by
  induction hf using Submodule.span_induction with
  | zero => simp
  | add a b _ _ ha hb => rw [add_mul]; exact Submodule.add_mem _ ha hb
  | smul c a _ ha => rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ ha
  | mem u hu =>
    obtain ⟨x, hx, rfl⟩ := hu
    induction hg using Submodule.span_induction with
    | zero => simp
    | add a b _ _ ha hb => rw [mul_add]; exact Submodule.add_mem _ ha hb
    | smul c a _ ha => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ ha
    | mem w hw =>
      obtain ⟨y, hy, rfl⟩ := hw
      have hx' : m ≤ x.2.2.length := hx
      have hy' : n ≤ y.2.2.length := hy
      simp only [coe_pathAlgebraBasis, ofPath_mul_ofPath]
      cases hxy : x.mul? y with
      | none => exact Submodule.zero_mem _
      | some z =>
        refine ofPath_mem_pathSpan ?_
        rw [Quiver.TotalPath.length_eq_add_of_mul?_eq_some hxy]
        omega

/-- Powers of an element of the first step of the length filtration climb the filtration. -/
theorem pow_mem_pathSpan [Finite Q] {f : pathAlgebra k Q} (hf : f ∈ pathSpan k Q 1) (n : ℕ) :
    f ^ n ∈ pathSpan k Q n := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pow_succ]
    exact mul_mem_pathSpan ih hf

end Multiplicative

section ArrowIdeal

variable (k : Type w) (Q : Type u) [CommSemiring k] [Quiver.{v} Q] [Finite Q]

/-- **The arrow ideal** of a path algebra: the elements whose coordinates on the trivial paths all
vanish, equivalently the `k`-span of the paths of positive length. It is the ideal generated by the
arrows of the quiver. -/
noncomputable def arrowIdeal : Ideal (pathAlgebra k Q) where
  carrier := (pathSpan k Q 1 : Set (pathAlgebra k Q))
  add_mem' ha hb := Submodule.add_mem _ ha hb
  zero_mem' := Submodule.zero_mem _
  smul_mem' c f hf := by
    simpa [smul_eq_mul] using mul_mem_pathSpan (mem_pathSpan_zero c) hf

variable {k Q}

/-- The arrow ideal is the first step of the length filtration. This is the bridge to the
implementation, kept private: consumers use the coordinate, basis-path, power and span-of-arrows
characterizations instead. -/
private theorem mem_arrowIdeal {f : pathAlgebra k Q} : f ∈ arrowIdeal k Q ↔ f ∈ pathSpan k Q 1 :=
  Iff.rfl

/-- **Membership in the arrow ideal**, read off the path basis: an element lies in the arrow ideal
exactly when every path carrying a nonzero coordinate has positive length. -/
theorem mem_arrowIdeal_iff {f : pathAlgebra k Q} :
    f ∈ arrowIdeal k Q ↔
      ∀ x : Quiver.TotalPath Q, (pathAlgebraBasis k Q).repr f x ≠ 0 → 0 < x.2.2.length :=
  mem_pathSpan_iff

/-- **Membership in the arrow ideal, as the vanishing of the trivial coordinates**: an element lies
in the arrow ideal exactly when its coordinate on the trivial path at each vertex vanishes. This is
the form to check membership against, the trivial paths being the only ones of length zero. -/
theorem mem_arrowIdeal_iff_repr_nil {f : pathAlgebra k Q} :
    f ∈ arrowIdeal k Q ↔
      ∀ v : Q, (pathAlgebraBasis k Q).repr f ⟨v, v, Quiver.Path.nil⟩ = 0 := by
  rw [mem_arrowIdeal_iff]
  constructor
  · intro h v
    by_contra hv
    simpa using h ⟨v, v, Quiver.Path.nil⟩ hv
  · intro h x hx
    by_contra hlen
    obtain ⟨a, b, p⟩ := x
    have hzero : p.length = 0 := Nat.le_zero.1 (Nat.not_lt.1 hlen)
    obtain rfl : a = b := p.eq_of_length_zero hzero
    obtain rfl : p = Quiver.Path.nil := p.eq_nil_of_length_zero hzero
    exact hx (h a)

/-- The arrow ideal is two-sided: appending a path to a path of positive length leaves its length
positive. -/
instance arrowIdeal.instIsTwoSided : (arrowIdeal k Q).IsTwoSided :=
  ⟨fun g hf => mem_arrowIdeal.2 (by
    simpa using mul_mem_pathSpan (mem_arrowIdeal.1 hf) (mem_pathSpan_zero g))⟩

/-- A path of positive length lies in the arrow ideal. -/
theorem ofPath_mem_arrowIdeal {x : Quiver.TotalPath Q} (hx : 0 < x.2.2.length) :
    (ofPath x : pathAlgebra k Q) ∈ arrowIdeal k Q :=
  ofPath_mem_pathSpan hx

/-- A basis path lies in the arrow ideal exactly when it has positive length: the arrow ideal
meets the path basis in the nontrivial paths. -/
@[simp]
theorem ofPath_mem_arrowIdeal_iff [Nontrivial k] {x : Quiver.TotalPath Q} :
    (ofPath x : pathAlgebra k Q) ∈ arrowIdeal k Q ↔ 0 < x.2.2.length :=
  ofPath_mem_pathSpan_iff

/-- No vertex idempotent lies in the arrow ideal: a trivial path has length zero. -/
theorem vertexIdempotent_notMem_arrowIdeal [Nontrivial k] (v : Q) :
    (vertexIdempotent k v : pathAlgebra k Q) ∉ arrowIdeal k Q := by
  intro hv
  have := mem_pathSpan_iff.1 hv ⟨v, v, Quiver.Path.nil⟩
  rw [vertexIdempotent_eq_single, pathAlgebraBasis_repr_single] at this
  simp at this

/-- An arrow lies in the arrow ideal. -/
theorem ofArrow_mem_arrowIdeal {a b : Q} (e : a ⟶ b) :
    (ofArrow e : pathAlgebra k Q) ∈ arrowIdeal k Q := by
  rw [ofArrow_eq_ofPath]
  exact ofPath_mem_arrowIdeal (by simp [Quiver.Path.length_toPath])

/-- A basis path lies in the power of the arrow ideal named by its length: a path is the product of
its arrows, one factor for each. -/
theorem ofPath_mem_arrowIdeal_pow (x : Quiver.TotalPath Q) :
    (ofPath x : pathAlgebra k Q) ∈ arrowIdeal k Q ^ x.2.2.length := by
  obtain ⟨a, b, p⟩ := x
  induction p with
  | nil =>
    rw [Quiver.Path.length_nil, Submodule.pow_zero, Ideal.one_eq_top]
    exact Submodule.mem_top
  | cons p e ih =>
    rw [Quiver.Path.length_cons, ← Quiver.Path.comp_toPath_eq_cons,
      ← ofPath_mul_ofPath_of_comp e.toPath p, ← ofArrow_eq_ofPath]
    -- The product writes the arrow *first*, so it is the last factor of the power that has to be
    -- split off, and `Submodule.pow_succ'` asks for a nonzero exponent.
    obtain hp | hp := Nat.eq_zero_or_pos p.length
    · rw [hp, Nat.zero_add, Submodule.pow_one]
      exact Ideal.mul_mem_right _ _ (ofArrow_mem_arrowIdeal e)
    · rw [Submodule.pow_succ' _ hp.ne']
      exact Submodule.mul_mem_mul (ofArrow_mem_arrowIdeal e) ih

/-- **The powers of the arrow ideal are the steps of the length filtration**, in terms of
membership: a product of `n` elements of the arrow ideal is supported on the paths of length at
least `n`, and conversely such a path is a product of `n` arrows and a shorter path. -/
theorem mem_arrowIdeal_pow {n : ℕ} {f : pathAlgebra k Q} :
    f ∈ arrowIdeal k Q ^ n ↔ f ∈ pathSpan k Q n := by
  refine ⟨?_, fun hf => ?_⟩
  · induction n generalizing f with
    | zero => exact fun _ => mem_pathSpan_zero f
    | succ n ih =>
      intro hf
      rw [Submodule.pow_succ] at hf
      exact Submodule.mul_induction_on hf
        (fun _ hx _ hy => mul_mem_pathSpan (ih hx) (mem_arrowIdeal.1 hy))
        fun _ _ hx hy => Submodule.add_mem _ hx hy
  · rw [pathSpan] at hf
    induction hf using Submodule.span_induction with
    | zero => exact Submodule.zero_mem _
    | add _ _ _ _ ha hb => exact Submodule.add_mem _ ha hb
    | smul c a _ ha =>
      rw [Algebra.smul_def]
      exact Ideal.mul_mem_left _ _ ha
    | mem u hu =>
      obtain ⟨x, hx, rfl⟩ := hu
      simp only [coe_pathAlgebraBasis]
      exact Ideal.pow_le_pow_right hx (ofPath_mem_arrowIdeal_pow x)

/-- **A basis path lies in the `n`-th power of the arrow ideal exactly when it has length at least
`n`**: the powers of the arrow ideal meet the path basis in the long enough paths. -/
@[simp]
theorem ofPath_mem_arrowIdeal_pow_iff [Nontrivial k] {n : ℕ} {x : Quiver.TotalPath Q} :
    (ofPath x : pathAlgebra k Q) ∈ arrowIdeal k Q ^ n ↔ n ≤ x.2.2.length :=
  mem_arrowIdeal_pow.trans ofPath_mem_pathSpan_iff

variable (k Q)

/-- **The arrow ideal is the ideal generated by the arrows**, which is what its name says. Every
path of positive length factors as a shorter path times its *first* arrow — the path algebra writes
the later factor first — so it is a left multiple of an arrow. -/
theorem arrowIdeal_eq_span_arrows :
    arrowIdeal k Q
      = Ideal.span (Set.range fun e : Σ a b : Q, a ⟶ b => (ofArrow e.2.2 : pathAlgebra k Q)) := by
  refine le_antisymm (fun f hf => ?_) (Ideal.span_le.2 ?_)
  · rw [mem_arrowIdeal, pathSpan] at hf
    induction hf using Submodule.span_induction with
    | zero => exact Submodule.zero_mem _
    | add _ _ _ _ ha hb => exact Submodule.add_mem _ ha hb
    | smul c a _ ha =>
      rw [Algebra.smul_def]
      exact Ideal.mul_mem_left _ _ ha
    | mem u hu =>
      obtain ⟨x, hx, rfl⟩ := hu
      obtain ⟨a, b, p⟩ := x
      obtain ⟨c, e, p', rfl, -⟩ := p.length_ne_zero_iff_eq_comp.1 (Nat.one_le_iff_ne_zero.1 hx)
      simp only [coe_pathAlgebraBasis]
      rw [← ofPath_mul_ofPath_of_comp p' e.toPath, ← ofArrow_eq_ofPath]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨⟨a, c, e⟩, rfl⟩)
  · rintro _ ⟨e, rfl⟩
    exact ofArrow_mem_arrowIdeal e.2.2

/-- **The length filtration is the filtration by the powers of the arrow ideal**: the `n`-th step
`pathSpan k Q n` is the `k`-submodule underlying `(arrowIdeal k Q) ^ n`. This is what makes every
step an ideal, and the form the radical powers are measured against. -/
theorem restrictScalars_arrowIdeal_pow (n : ℕ) :
    (arrowIdeal k Q ^ n).restrictScalars k = pathSpan k Q n :=
  SetLike.ext fun _ => mem_arrowIdeal_pow

variable {k Q}

/-- **Every element of the arrow ideal of a finite acyclic quiver is nilpotent**: its
`Nat.card Q`-th power lies in a step of the length filtration that has already died. -/
theorem isNilpotent_of_mem_arrowIdeal (h : Quiver.IsAcyclic Q) {f : pathAlgebra k Q}
    (hf : f ∈ arrowIdeal k Q) : IsNilpotent f :=
  ⟨Nat.card Q, by
    have := pow_mem_pathSpan (mem_arrowIdeal.1 hf) (Nat.card Q)
    rwa [pathSpan_eq_bot_of_isAcyclic k Q h, Submodule.mem_bot] at this⟩

end ArrowIdeal

section Jacobson

variable {k : Type w} {Q : Type u} [Field k] [Quiver.{v} Q] [Finite Q]

/-- **The arrow ideal of a finite acyclic quiver is contained in the Jacobson radical.** A maximal
left ideal that missed the arrow ideal would join with it to the whole algebra, writing `1` as a
sum of an element of the maximal ideal and a nilpotent, and hence containing a unit. -/
theorem arrowIdeal_le_jacobson {k : Type w} [CommRing k] (h : Quiver.IsAcyclic Q) :
    arrowIdeal k Q ≤ Ring.jacobson (pathAlgebra k Q) := by
  rw [Ring.jacobson_eq_sInf_isMaximal]
  refine le_sInf fun m hm => ?_
  have hcoatom : IsCoatom m := Ideal.isMaximal_def.1 hm
  by_contra hle
  have hlt : m < m ⊔ arrowIdeal k Q :=
    lt_of_le_of_ne le_sup_left fun heq => hle (heq ▸ le_sup_right)
  obtain ⟨y, hy, z, hz, hyz⟩ :=
    Submodule.mem_sup.1 (hcoatom.2 _ hlt ▸ Submodule.mem_top : (1 : pathAlgebra k Q) ∈ _)
  have hunit : IsUnit y := by
    have hy' : y = 1 - z := eq_sub_of_add_eq hyz
    exact hy' ▸ (isNilpotent_of_mem_arrowIdeal h hz).isUnit_one_sub
  refine hcoatom.1 (Ideal.eq_top_iff_one _ |>.2 ?_)
  obtain ⟨u, rfl⟩ := hunit
  simpa using m.smul_mem (↑u⁻¹ : pathAlgebra k Q) hy

/-- No vertex idempotent lies in the Jacobson radical: it is a nonzero idempotent, so `1 - eᵥ` is
not a unit, and the left ideal it generates is contained in a maximal one that would then contain
`1`. -/
theorem vertexIdempotent_notMem_jacobson {k : Type w} [Ring k] [Nontrivial k] (v : Q) :
    (vertexIdempotent k v : pathAlgebra k Q) ∉ Ring.jacobson (pathAlgebra k Q) := by
  intro hv
  have hne : (vertexIdempotent k v : pathAlgebra k Q) ≠ 0 := vertexIdempotent_ne_zero v
  have hproper : Ideal.span {1 - vertexIdempotent k v} ≠ (⊤ : Ideal (pathAlgebra k Q)) := by
    intro htop
    have hone : (1 : pathAlgebra k Q) ∈ Ideal.span {1 - vertexIdempotent k v} := by
      rw [htop]; exact Submodule.mem_top
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.1 hone
    apply hne
    have hmul := congrArg (· * vertexIdempotent k v) hc
    simpa [mul_assoc, mul_sub, sub_mul] using hmul.symm
  obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal _ hproper
  refine hm.ne_top (Ideal.eq_top_iff_one _ |>.2 ?_)
  have h₁ : (1 : pathAlgebra k Q) - vertexIdempotent k v ∈ m :=
    hle (Ideal.subset_span rfl)
  have h₂ : (vertexIdempotent k v : pathAlgebra k Q) ∈ m := Ring.jacobson_le_of_isMaximal m hv
  simpa using m.add_mem h₁ h₂

/-- **The Jacobson radical of the path algebra of a finite acyclic quiver is its arrow ideal.**

The arrow ideal is nilpotent, hence inside the radical. Conversely an element `f` of the radical
has `eᵥ f eᵥ` in the radical for every vertex `v`, and that element is the coordinate of `f` on the
trivial path at `v` times `eᵥ`; were the coordinate nonzero, `eᵥ` itself would lie in the radical,
which it does not. -/
theorem jacobson_pathAlgebra_eq_arrowIdeal (k : Type w) (Q : Type u) [Field k] [Quiver.{v} Q]
    [Finite Q] (h : Quiver.IsAcyclic Q) :
    Ring.jacobson (pathAlgebra k Q) = arrowIdeal k Q := by
  refine le_antisymm (fun f hf => mem_arrowIdeal.2 (mem_pathSpan_iff.2 fun x hx => ?_))
    (arrowIdeal_le_jacobson h)
  by_contra hlen
  obtain ⟨a, b, p⟩ := x
  have hzero : p.length = 0 := Nat.lt_one_iff.1 (Nat.not_le.1 hlen)
  obtain rfl : a = b := p.eq_of_length_zero hzero
  obtain rfl : p = Quiver.Path.nil := p.eq_nil_of_length_zero hzero
  refine vertexIdempotent_notMem_jacobson (k := k) a ?_
  have hmem : (pathAlgebraBasis k Q).repr f ⟨a, a, Quiver.Path.nil⟩ • vertexIdempotent k a
      ∈ Ring.jacobson (pathAlgebra k Q) := by
    rw [← vertexIdempotent_mul_mul_vertexIdempotent a h.eq_nil f]
    exact Ideal.mul_mem_right _ _ (Ideal.mul_mem_left _ _ hf)
  have hscale := Ideal.mul_mem_left (Ring.jacobson (pathAlgebra k Q))
    (algebraMap k (pathAlgebra k Q) ((pathAlgebraBasis k Q).repr f ⟨a, a, Quiver.Path.nil⟩)⁻¹) hmem
  rwa [Algebra.smul_def, ← mul_assoc, ← map_mul, inv_mul_cancel₀ hx, map_one, one_mul] at hscale

end Jacobson

end TauCeti
