/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Degree
public import Mathlib.FieldTheory.Galois.Basic
public import Mathlib.GroupTheory.Exponent
import TauCeti.NumberTheory.Multiquadratic.Quadratic.Subfield
import TauCeti.GroupTheory.ExponentPrime
import TauCeti.FieldTheory.Galois.SquareRoot
import Mathlib.FieldTheory.PrimitiveElement

/-!
# An exponent-two Galois extension is multiquadratic

`TauCeti/NumberTheory/Multiquadratic/Galois` shows that adjoining square roots of a square-class
independent family gives a Galois extension (`TauCeti.Multiquadratic.isGalois`) whose group has
exponent two (`TauCeti.Multiquadratic.aut_exponent_dvd_two`), while
`TauCeti/NumberTheory/Multiquadratic/Degree` computes its degree as `2ⁿ`
(`TauCeti.Multiquadratic.finrank_adjoin_range`). This file proves the **converse**, which is
exponent-two Kummer theory: over a field where `2 ≠ 0`, a finite Galois extension whose group has
exponent two is generated by square roots of elements of the base field, and one can take the
radicands square-class independent, so the degree is again `2ⁿ`.

The argument is the Galois correspondence plus one linear-algebra fact about the group,
`TauCeti.exists_le_index_eq_two_notMem_of_exponent_dvd_two`: a subgroup of an elementary abelian
`2`-group avoiding an element lies in an index-two subgroup avoiding that element. The fixed
field of such a subgroup is quadratic over `K`, hence generated by a square root
(`TauCeti.IntermediateField.exists_sq_mem_range_adjoin_simple_eq_of_finrank_eq_two`, where
completing the square is what needs `2 ≠ 0`). This gives
`TauCeti.Multiquadratic.exists_sq_mem_range_apply_eq_neg_of_notMem`: a nonzero square root fixed
by the original subgroup and negated by the chosen automorphism. If some `σ ≠ 1` fixed every
square root, this lemma with the trivial subgroup would give a nonzero `x` both fixed and
negated by `σ`, so `2 * x = 0`, a contradiction. Thus the square roots generate, and
finite-dimensionality cuts the generating set down to a finite one.

Square-class independence is then a *minimality* statement rather than extra work: choosing a
generating set of square roots of least cardinality, a square subset product would express one of
its members through the others, and dropping it would give a smaller generating set. Feeding the
independent family back into `TauCeti.Multiquadratic.finrank_adjoin_range` gives `[L : K] = 2ⁿ`.

This is the ingredient the genus-field milestone of `TauCetiRoadmap/Multiquadratic/README.md`
(Layer 3) calls for. The maximality half of the identification of `candidateGenusField` with the
genus field starts from an extension `M` of `K = ℚ(√d)` that is unramified everywhere and abelian
over `ℚ`; because `ℚ` has no unramified extension, the inertia subgroups generate `Gal(M/ℚ)` and
each of them meets `Gal(M/K)` trivially, so `Gal(M/ℚ)` has exponent two. What this file supplies is
the step from there: such an `M` is a compositum of quadratic fields, so Layer 0 applies to it.

Exponent-two Kummer theory is classical; see for instance S. Lang, *Algebra*, VI §8, or
D. A. Cox, *Primes of the Form x² + ny²*, §6.A, where the genus field is described exactly this
way.

## Main results

In the namespace `TauCeti.Multiquadratic`:

* `exists_sq_mem_range_apply_eq_neg_of_notMem`: separate an automorphism from a subgroup
  by a nonzero square root fixed by that subgroup and negated by the automorphism.
* `adjoin_setOf_sq_mem_range_eq_top`: the square roots of elements of `K` that lie in `L`
  generate `L` over `K`.
* `exists_finset_sq_mem_range_adjoin_eq_top`: a *finite* set of such square roots already
  generates.
* `exists_root_adjoin_eq_adjoin`: any finite family of square roots can be replaced by a
  square-class independent family generating the same intermediate field.
* `exists_root_adjoin_range_eq_top`: the sharp form — `L = K(√d₁, …, √dₙ)` for a square-class
  independent family, and consequently `[L : K] = 2ⁿ`.
-/

public section

open Module

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- A product of chosen square roots is one of the two square roots of the radicand product. -/
private theorem prod_root_eq_or_eq_neg_of_prod_eq_mul_self {K L : Type*} [CommSemiring K]
    [CommRing L] [NoZeroDivisors L] [Algebra K L] {ι : Type*} {d : ι → K} {root : ι → L}
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i)) (S : Finset ι) {c : K}
    (hc : ∏ i ∈ S, d i = c * c) :
    (∏ i ∈ S, root i) = algebraMap K L c ∨ (∏ i ∈ S, root i) = -algebraMap K L c := by
  classical
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [prod_root_sq hroot S, hc, map_mul, ← sq]

/-- Minimality among square-root generating sets forces each member outside the field generated by
the remaining members; `hmin` compares `s` with every square-root set generating the same field. -/
private theorem notMem_adjoin_erase [DecidableEq L] {s : Finset L}
    (hssq : ∀ x ∈ s, ∃ a : K, x ^ 2 = algebraMap K L a)
    (hmin : ∀ t : Finset L, (∀ x ∈ t, ∃ a : K, x ^ 2 = algebraMap K L a) →
      IntermediateField.adjoin K (t : Set L) = IntermediateField.adjoin K (s : Set L) →
      s.card ≤ t.card) {x : L} (hx : x ∈ s) :
    x ∉ IntermediateField.adjoin K ((s.erase x : Finset L) : Set L) := by
  classical
  intro hxadj
  have hadjoin : IntermediateField.adjoin K ((s.erase x : Finset L) : Set L) =
      IntermediateField.adjoin K (s : Set L) :=
    le_antisymm (IntermediateField.adjoin.mono _ _ _ (by
      exact_mod_cast Finset.erase_subset x s))
      (IntermediateField.adjoin_le_iff.mpr fun y hy => (eq_or_ne y x).elim
        (fun h => h ▸ hxadj)
        (fun h => IntermediateField.subset_adjoin _ _ (by simp [h, hy])))
  have hcard := hmin _ (fun y hy => hssq y (Finset.mem_of_mem_erase hy)) hadjoin
  rw [Finset.card_erase_of_mem hx] at hcard
  have hpos : 0 < s.card := Finset.card_pos.mpr ⟨x, hx⟩
  omega

/-- Choose a least-cardinality square-root set generating the same field as `s`; its minimality
also forces it not to contain zero. -/
private theorem exists_minimal_sq_generators (s : Finset L)
    (hssq : ∀ x ∈ s, ∃ a : K, x ^ 2 = algebraMap K L a) :
    ∃ t : Finset L, (∀ x ∈ t, ∃ a : K, x ^ 2 = algebraMap K L a) ∧
      IntermediateField.adjoin K (t : Set L) = IntermediateField.adjoin K (s : Set L) ∧
      (∀ u : Finset L, (∀ x ∈ u, ∃ a : K, x ^ 2 = algebraMap K L a) →
        IntermediateField.adjoin K (u : Set L) = IntermediateField.adjoin K (s : Set L) →
        t.card ≤ u.card) ∧ 0 ∉ t := by
  classical
  have hex : ∃ m, ∃ t : Finset L, t.card = m ∧
      (∀ x ∈ t, ∃ a : K, x ^ 2 = algebraMap K L a) ∧
      IntermediateField.adjoin K (t : Set L) = IntermediateField.adjoin K (s : Set L) :=
    ⟨s.card, s, rfl, hssq, rfl⟩
  obtain ⟨t, htcard, htsq, htadj⟩ := Nat.find_spec hex
  have hmin : ∀ u : Finset L, (∀ x ∈ u, ∃ a : K, x ^ 2 = algebraMap K L a) →
      IntermediateField.adjoin K (u : Set L) = IntermediateField.adjoin K (s : Set L) →
      t.card ≤ u.card := fun u hu hadj => htcard ▸ Nat.find_le ⟨u, rfl, hu, hadj⟩
  have hzero : (0 : L) ∉ t := fun h0 => notMem_adjoin_erase htsq
    (fun u hu hadj => hmin u hu (hadj.trans htadj)) h0 (zero_mem _)
  exact ⟨t, htsq, htadj, hmin, hzero⟩

/-- A subgroup of an exponent-two finite Galois group avoiding `σ` fixes a nonzero square root
of an element of the base field that `σ` negates. -/
theorem exists_sq_mem_range_apply_eq_neg_of_notMem [FiniteDimensional K L] [IsGalois K L]
    [NeZero (2 : K)] (hexp : Monoid.exponent (L ≃ₐ[K] L) ∣ 2)
    {N : Subgroup (L ≃ₐ[K] L)} {σ : L ≃ₐ[K] L} (hσ : σ ∉ N) :
    ∃ (x : L) (a : K), x ≠ 0 ∧ x ^ 2 = algebraMap K L a ∧
      (∀ τ ∈ N, τ x = x) ∧ σ x = -x := by
  obtain ⟨H, hNH, hH, hσH⟩ := exists_le_index_eq_two_notMem_of_exponent_dvd_two hexp hσ
  obtain ⟨x, a, hx, hxa, hstab⟩ :=
    TauCeti.IntermediateField.exists_sq_mem_range_apply_eq_self_iff_of_index_eq_two hH
  exact ⟨x, a, hx, hxa, fun τ hτ => (hstab τ).mpr (hNH hτ),
    (AlgEquiv.apply_eq_or_eq_neg_of_sq_eq σ hxa).resolve_left
      (fun h => hσH ((hstab σ).mp h))⟩

/-- **An exponent-two Galois extension is generated by square roots.** If `2 ≠ 0` in `K` and
`L / K` is a finite Galois extension whose Galois group has exponent dividing two, then `L` is
generated over `K` by the elements whose square lies in `K`. -/
theorem adjoin_setOf_sq_mem_range_eq_top [FiniteDimensional K L] [IsGalois K L] [NeZero (2 : K)]
    (hexp : Monoid.exponent (L ≃ₐ[K] L) ∣ 2) :
    IntermediateField.adjoin K {x : L | ∃ a : K, x ^ 2 = algebraMap K L a} = ⊤ := by
  set M : IntermediateField K L :=
    IntermediateField.adjoin K {x : L | ∃ a : K, x ^ 2 = algebraMap K L a}
  -- No nontrivial automorphism fixes every square root.
  have hfix : M.fixingSubgroup = ⊥ := by
    rw [eq_bot_iff]
    intro σ hσ
    rw [Subgroup.mem_bot]
    by_contra hne
    obtain ⟨x, a, hx, hxa, -, hσx⟩ :=
      exists_sq_mem_range_apply_eq_neg_of_notMem hexp (N := ⊥) (by simpa using hne)
    have hxM : x ∈ M := IntermediateField.subset_adjoin K _ ⟨a, hxa⟩
    have hfixx : σ x = x := (IntermediateField.mem_fixingSubgroup_iff M σ).mp hσ x hxM
    -- `σ` both fixes and negates `x`, so `2 * x = 0` contradicts `hx` when `2 ≠ 0`.
    have : NeZero (2 : L) := NeZero.nat_of_injective (n := 2)
      (f := algebraMap K L) (algebraMap K L).injective
    exact hx ((mul_eq_zero.mp (by linear_combination hσx - hfixx : (2 : L) * x = 0)).resolve_left
      (NeZero.ne (2 : L)))
  have h := IsGalois.fixedField_fixingSubgroup M
  rw [hfix, IntermediateField.fixedField_bot] at h
  exact h.symm

/-- **Finitely many square roots already generate.** The generating set of
`adjoin_setOf_sq_mem_range_eq_top` can be taken finite, because `L / K` is finite: a primitive
element already lies in the subfield generated by finitely many square roots. -/
theorem exists_finset_sq_mem_range_adjoin_eq_top [FiniteDimensional K L] [IsGalois K L]
    [NeZero (2 : K)] (hexp : Monoid.exponent (L ≃ₐ[K] L) ∣ 2) :
    ∃ s : Finset L, (∀ x ∈ s, ∃ a : K, x ^ 2 = algebraMap K L a) ∧
      IntermediateField.adjoin K (s : Set L) = ⊤ := by
  obtain ⟨α, hα⟩ := Field.exists_primitive_element K L
  have hmem : α ∈ IntermediateField.adjoin K {x : L | ∃ a : K, x ^ 2 = algebraMap K L a} := by
    rw [adjoin_setOf_sq_mem_range_eq_top hexp]
    exact IntermediateField.mem_top
  obtain ⟨s, hs, hαs⟩ := IntermediateField.exists_finset_of_mem_adjoin hmem
  refine ⟨s, fun x hx => hs (Finset.mem_coe.mpr hx), ?_⟩
  rw [eq_top_iff, ← hα]
  exact IntermediateField.adjoin_simple_le_iff.mpr hαs

/-- **A finite family of square roots can be replaced by an independent generating family.** If
every member of a finite set `s` squares into `K`, then the field it generates has a presentation
by a square-class independent family of square roots. Its degree is therefore a power of two. The
new family generates the same field but need not be drawn from `s`. -/
theorem exists_root_adjoin_eq_adjoin [NeZero (2 : K)] (s : Finset L)
    (hssq : ∀ x ∈ s, ∃ a : K, x ^ 2 = algebraMap K L a) :
    ∃ (n : ℕ) (d : Fin n → K) (root : Fin n → L),
      (∀ i, root i ^ 2 = algebraMap K L (d i)) ∧
      (∀ S : Finset (Fin n), S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) ∧
      IntermediateField.adjoin K (Set.range root) = IntermediateField.adjoin K (s : Set L) ∧
      finrank K (IntermediateField.adjoin K (s : Set L)) = 2 ^ n := by
  classical
  obtain ⟨t, htsq, htadj, hmin, hzero⟩ := exists_minimal_sq_generators s hssq
  -- Index the chosen square roots by `Fin t.card` and name their radicands.
  set e : Fin t.card ≃ {x // x ∈ t} := t.equivFin.symm
  set root : Fin t.card → L := fun i => (e i : L) with hroot_def
  have hroot_inj : Function.Injective root := fun _ _ hij => e.injective (Subtype.ext hij)
  have hroot_mem : ∀ i, root i ∈ t := fun i => (e i).2
  choose d hd using fun i : Fin t.card => htsq (root i) (hroot_mem i)
  have hrange : Set.range root = (t : Set L) := by
    ext x
    refine ⟨?_, fun hx => ⟨e.symm ⟨x, Finset.mem_coe.mp hx⟩, by simp [hroot_def]⟩⟩
    rintro ⟨i, rfl⟩
    exact Finset.mem_coe.mpr (hroot_mem i)
  have hadjoin : IntermediateField.adjoin K (Set.range root) =
      IntermediateField.adjoin K (s : Set L) := by rw [hrange]; exact htadj
  -- Square-class independence, by minimality.
  have hindep : ∀ S : Finset (Fin t.card), S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i) := by
    rintro S ⟨i₀, hi₀⟩ ⟨c, hc⟩
    -- The product of the roots over `S` is `± c`, so `root i₀` lies in the field the others span.
    set F : IntermediateField K L :=
      IntermediateField.adjoin K ((t.erase (root i₀) : Finset L) : Set L)
    have hmemF : ∀ i ∈ S.erase i₀, root i ∈ F :=
      fun i hi => IntermediateField.subset_adjoin K _ (Finset.mem_coe.mpr
        (Finset.mem_erase.mpr ⟨fun h => (Finset.mem_erase.mp hi).1 (hroot_inj h),
          hroot_mem i⟩))
    have hne : ∀ i, root i ≠ 0 := fun i h => hzero (h ▸ hroot_mem i)
    set P : L := ∏ i ∈ S.erase i₀, root i with hP
    have hPmem : P ∈ F := Subalgebra.prod_mem _ fun i hi => hmemF i hi
    have hPne : P ≠ 0 := Finset.prod_ne_zero_iff.mpr fun i _ => hne i
    have hprod : root i₀ * P = algebraMap K L c ∨ root i₀ * P = -algebraMap K L c := by
      rw [hP, Finset.mul_prod_erase S root hi₀]
      exact prod_root_eq_or_eq_neg_of_prod_eq_mul_self hd S hc
    have hi₀F : root i₀ ∈ F := by
      have hkey : root i₀ = (root i₀ * P) * P⁻¹ := by
        rw [mul_assoc, mul_inv_cancel₀ hPne, mul_one]
      rw [hkey]
      refine mul_mem ?_ (inv_mem hPmem)
      rcases hprod with h | h
      · rw [h]; exact IntermediateField.algebraMap_mem _ _
      · rw [h]; exact neg_mem (IntermediateField.algebraMap_mem _ _)
    exact notMem_adjoin_erase htsq
      (fun u hu huadj => hmin u hu (huadj.trans htadj)) (hroot_mem i₀) hi₀F
  refine ⟨t.card, d, root, hd, hindep, hadjoin, ?_⟩
  rw [← hadjoin]
  simpa [Nat.card_eq_fintype_card] using finrank_adjoin_range (K := K) (L := L) hd hindep

/-- **The converse of the multiquadratic degree theorem.** Let `2 ≠ 0` in `K` and let `L / K` be a
finite Galois extension whose Galois group has exponent dividing two. Then `L = K(√d₁, …, √dₙ)`
for radicands `d₁, …, dₙ ∈ K` that are square-class independent — no nonempty subset product is a
square — and consequently `[L : K] = 2ⁿ`. -/
theorem exists_root_adjoin_range_eq_top [FiniteDimensional K L] [IsGalois K L] [NeZero (2 : K)]
    (hexp : Monoid.exponent (L ≃ₐ[K] L) ∣ 2) :
    ∃ (n : ℕ) (d : Fin n → K) (root : Fin n → L),
      (∀ i, root i ^ 2 = algebraMap K L (d i)) ∧
      (∀ S : Finset (Fin n), S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) ∧
      IntermediateField.adjoin K (Set.range root) = ⊤ ∧
      finrank K L = 2 ^ n := by
  obtain ⟨s, hssq, hstop⟩ := exists_finset_sq_mem_range_adjoin_eq_top hexp
  obtain ⟨n, d, root, hd, hindep, hadjoin, hfin⟩ :=
    exists_root_adjoin_eq_adjoin s hssq
  refine ⟨n, d, root, hd, hindep, hadjoin.trans hstop, ?_⟩
  rw [hstop, IntermediateField.finrank_top'] at hfin
  exact hfin

end TauCeti.Multiquadratic
