/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.SquareClass.Independence

/-!
# The degree of a multiquadratic field with arbitrary unit radicands

`TauCeti.Multiquadratic.finrank_adjoin_range` computes `[K(rootᵢ : i) : K] = 2^|ι|` for
**square-class independent** radicands. Without that hypothesis the degree is still a power of
two, and the exponent measures how independent the radicands are: it is the rank of the subgroup
of the square-class group `Kˣ ⧸ (Kˣ)²` generated by their classes. Independence is the case
where that rank is `|ι|`, so this recovers the degree theorem, and it also covers families with
relations, where each independent relation among the classes halves the degree.

## Main results

* `TauCeti.Multiquadratic.mem_adjoin_of_squareClass_mem_span`: if the class of a radicand lies in
  the span of the classes of a subfamily, its root already lies in the field the subfamily
  generates. This is the converse of square-class descent
  (`TauCeti.Multiquadratic.squareClass_of_sq_mem`).
* `TauCeti.Multiquadratic.finrank_adjoin_range_eq_two_pow_finrank_span_squareClass`:
  `[K(rootᵢ : i) : K] = 2 ^ finrank (span of the square classes of the radicands)`, with no
  independence hypothesis.

## Provenance

The statement in terms of the square-class rank, the converse-descent step, and the reduction to
a maximal independent subfamily follow the multiquadratic development in
[MichaelStollBayreuth/QuadraticIterates](https://github.com/MichaelStollBayreuth/QuadraticIterates)
(`QuadraticIterates/Mathlib/FieldTheory/Multiquadratic.lean`, `finrank_adjoin_range_eq_two_pow_sub`
and its relation-space API), written for the formalization of M. Stoll, *Galois groups over `ℚ` of
some iterated polynomials*, Arch. Math. **59** (1992), 239-244. That development proves the degree
formula by induction over the index set; the proof here instead reduces to
`TauCeti.Multiquadratic.finrank_adjoin_range_of_linearIndependent` on a maximal independent
subfamily.
-/

public section

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K]

section Semiring

variable [Semiring L] [Nontrivial L] [Algebra K L]

/-- A root of a unit radicand is nonzero. -/
private theorem root_ne_zero {ι : Type*} {d : ι → Kˣ} {root : ι → L}
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i)) (i : ι) : root i ≠ 0 := by
  intro h
  have h2 := hroot i
  rw [h, zero_pow two_ne_zero] at h2
  exact (d i).ne_zero ((algebraMap K L).injective (by rw [← h2, map_zero]))

end Semiring

variable [Field L] [Algebra K L]

/-- The only nonzero element of `ZMod 2` is `1`. -/
private theorem eq_one_of_ne_zero {t : ZMod 2} (ht : t ≠ 0) : t = 1 := by
  revert ht; revert t; decide

/-- **The converse of square-class descent.** If the square class of the radicand `d i` lies in
the span of the square classes of the radicands indexed by `s`, then the root `root i` lies in
the field generated over `K` by the roots indexed by `s`. -/
theorem mem_adjoin_of_squareClass_mem_span {ι : Type*} {d : ι → Kˣ} {root : ι → L}
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i)) {s : Set ι} {i : ι}
    (hmem : squareClass (d i) ∈
      Submodule.span (ZMod 2) ((fun j => squareClass (d j)) '' s)) :
    root i ∈ IntermediateField.adjoin K (Set.range fun j : s => root j) := by
  classical
  set F := IntermediateField.adjoin K (Set.range fun j : s => root j)
  -- The class of `d i` is the class of a subset product of the radicands indexed by `s`.
  rw [Set.image_eq_range] at hmem
  obtain ⟨c, hc⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp hmem
  set S : Finset ι := c.support.image Subtype.val with hS
  have hSs : ↑S ⊆ s := by
    intro j hj
    simp only [hS, Finset.coe_image, Set.mem_image, Finset.mem_coe] at hj
    obtain ⟨x, -, rfl⟩ := hj
    exact x.2
  have hclass : squareClass (d i) = squareClass (∏ j ∈ S, d j) := by
    rw [squareClass_prod, hS, Finset.sum_image (fun _ _ _ _ h => Subtype.ext h), ← hc, Finsupp.sum]
    refine Finset.sum_congr rfl fun x hx => ?_
    rw [eq_one_of_ne_zero (Finsupp.mem_support_iff.mp hx), one_smul]
  -- Hence `d i` times that subset product is a square in `K`.
  have hsq : IsSquare (d i * ∏ j ∈ S, d j) := by
    rw [← squareClass_eq_zero_iff, squareClass_mul, ← hclass, ← two_smul (ZMod 2),
      CharTwo.two_eq_zero (R := ZMod 2), zero_smul]
  obtain ⟨u, hu⟩ := hsq
  -- The product of the roots indexed by `S` lies in `F` and is nonzero.
  set y : L := ∏ j ∈ S, root j with hy
  have hyF : y ∈ F := Subring.prod_mem _ fun j hj =>
    IntermediateField.subset_adjoin _ _ ⟨⟨j, hSs hj⟩, rfl⟩
  have hy0 : y ≠ 0 := Finset.prod_ne_zero_iff.mpr fun j _ => root_ne_zero hroot j
  -- `root i * y` squares to the square of `algebraMap K L u`, so it is `± algebraMap K L u`.
  have hsq2 : (root i * y) ^ 2 = algebraMap K L (u : K) ^ 2 := by
    rw [mul_pow, hroot i, hy, ← Finset.prod_pow,
      Finset.prod_congr rfl (fun j _ => hroot j), ← map_prod, ← map_mul, ← map_pow]
    congr 1
    have hval : ((d i * ∏ j ∈ S, d j : Kˣ) : K) = ((u * u : Kˣ) : K) := by rw [hu]
    push_cast at hval ⊢
    rw [hval]
    ring
  have huF : algebraMap K L (u : K) ∈ F := F.algebraMap_mem _
  -- Dividing that identity by `y` exhibits `root i` inside `F`.
  have key {z : L} (hz : z ∈ F) (h : root i * y = z) : root i ∈ F := by
    have hzy : z * y⁻¹ = root i := by rw [← h, mul_inv_cancel_right₀ hy0]
    exact hzy ▸ F.mul_mem hz (F.inv_mem hyF)
  rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq2 with h | h
  · exact key huF h
  · exact key (F.neg_mem huF) h

/-- **The degree of a multiquadratic field, with no independence hypothesis.** The field generated
over `K` by square roots `root i` of the units `d i` has degree `2 ^ r` over `K`, where `r` is the
rank of the subgroup of the square-class group `Kˣ ⧸ (Kˣ)²` generated by the classes of the
radicands. `TauCeti.Multiquadratic.finrank_adjoin_range_of_linearIndependent` is the case where
those classes are independent, so that `r = |ι|`. -/
theorem finrank_adjoin_range_eq_two_pow_finrank_span_squareClass {ι : Type*} [Finite ι] {d : ι → Kˣ}
    {root : ι → L} (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i)) [NeZero (2 : K)] :
    Module.finrank K (IntermediateField.adjoin K (Set.range root)) =
      2 ^ Module.finrank (ZMod 2)
        (Submodule.span (ZMod 2) (Set.range fun i => squareClass (d i))) := by
  classical
  let := Fintype.ofFinite ι
  obtain ⟨s, hs, hmax⟩ := exists_maximal_linearIndepOn (ZMod 2) fun i => squareClass (d i)
  let := Fintype.ofFinite s
  -- Every square class lies in the span of the classes indexed by the maximal independent `s`.
  have hmem : ∀ i, squareClass (d i) ∈
      Submodule.span (ZMod 2) ((fun j => squareClass (d j)) '' s) := by
    intro i
    by_cases hi : i ∈ s
    · exact Submodule.subset_span ⟨i, hi, rfl⟩
    · obtain ⟨a, ha, hmem⟩ := hmax i hi
      rwa [eq_one_of_ne_zero ha, one_smul] at hmem
  have hspan : Submodule.span (ZMod 2) (Set.range fun i => squareClass (d i))
      = Submodule.span (ZMod 2) ((fun j => squareClass (d j)) '' s) :=
    le_antisymm (Submodule.span_le.mpr (Set.range_subset_iff.mpr hmem))
      (Submodule.span_mono (Set.image_subset_range _ _))
  -- The roots indexed by `s` generate the whole field.
  have hfield : IntermediateField.adjoin K (Set.range root)
      = IntermediateField.adjoin K (Set.range fun j : s => root j) := by
    refine le_antisymm (IntermediateField.adjoin_le_iff.mpr ?_)
      (IntermediateField.adjoin_le_iff.mpr ?_)
    · rintro _ ⟨i, rfl⟩
      exact mem_adjoin_of_squareClass_mem_span hroot (hmem i)
    · rintro _ ⟨j, rfl⟩
      exact IntermediateField.subset_adjoin _ _ ⟨(j : ι), rfl⟩
  rw [hfield, finrank_adjoin_range_of_linearIndependent (d := fun j : s => d j)
    (fun j => hroot j) hs, hspan, Set.image_eq_range, finrank_span_eq_card hs,
    Nat.card_eq_fintype_card]

end TauCeti.Multiquadratic
